## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import functions as fx;
import functions as fx
# (Line 3) const s = StringBuffer(1024);
s = _CGFW(lambda: [StringBuffer(1024)], 1)[0]
# (Line 5) function finale() {
@EUDFunc
def f_finale():
    # (Line 6) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 7) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 8) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 9) CenterView("Story");
        # (Line 11) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 12) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 13) }
            # (Line 15) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 16) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 17) }
            # (Line 19) if(fx.timer(68, 72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(68, 72)):
            # (Line 20) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 21) }
            # (Line 23) if(fx.timer(72, 240)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 240)):
            # (Line 24) s.printAt(0, "\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 25) s.printAt(8, "\x13\x04일기장을 다 읽고 그녀의 집을 수색하는 도중");
            s.printAt(8, "\x13\x04일기장을 다 읽고 그녀의 집을 수색하는 도중")
            # (Line 26) }
            # (Line 27) if(fx.timer(144,240)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(144, 240)):
            # (Line 28) s.printAt(9, "\x13\x04대문에서 누군가가 문을 두들기는 소리가 났다.");
            s.printAt(9, "\x13\x04대문에서 누군가가 문을 두들기는 소리가 났다.")
            # (Line 29) }
            # (Line 30) if(fx.timer(240,264)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(240, 264)):
            # (Line 31) s.print("\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n")
            # (Line 32) }
            # (Line 34) if(fx.timer(264,360)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(264, 360)):
            # (Line 35) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 36) s.fadeIn("\x13\x11안녕하십니까, 혹시 \x04Cedar \x11탐정님이십니까?", wait=2, line=9);
            s.fadeIn("\x13\x11안녕하십니까, 혹시 \x04Cedar \x11탐정님이십니까?", wait=2, line=9)
            # (Line 37) }
            # (Line 39) if(fx.timer(360,408)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(360, 408)):
            # (Line 40) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 41) s.printAt(9, "\x13\x04그렇습니다만");
            s.printAt(9, "\x13\x04그렇습니다만")
            # (Line 42) }
            # (Line 44) if(fx.timer(408,504)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(408, 504)):
            # (Line 45) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 46) s.fadeIn("\x13\x11저는 Birdsfoot라고 하는 심령술사입니다.", wait=3, line=9);
            s.fadeIn("\x13\x11저는 Birdsfoot라고 하는 심령술사입니다.", wait=3, line=9)
            # (Line 47) }
            # (Line 48) if(fx.timer(504,600)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(504, 600)):
            # (Line 49) s.printAt(0,"\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 50) s.printAt(8, "\x13\x11저는 Birdsfoot라고 하는 심령술사입니다.");
            s.printAt(8, "\x13\x11저는 Birdsfoot라고 하는 심령술사입니다.")
            # (Line 51) s.fadeIn("\x13\x11제 \x04쪽지\x11를 받으셨나 보군요.", wait=4, line=9);
            s.fadeIn("\x13\x11제 \x04쪽지\x11를 받으셨나 보군요.", wait=4, line=9)
            # (Line 52) }
            # (Line 54) if(fx.timer(600,672)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(600, 672)):
            # (Line 55) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 56) s.fadeIn("\x13\x11일기를 통해 알 수 있듯이",wait=4, line=9);
            s.fadeIn("\x13\x11일기를 통해 알 수 있듯이", wait=4, line=9)
            # (Line 57) }
            # (Line 58) if(fx.timer(672,768)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(672, 768)):
            # (Line 59) s.printAt(0,"\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 60) s.printAt(8, "\x13\x11일기를 통해 알 수 있듯이");
            s.printAt(8, "\x13\x11일기를 통해 알 수 있듯이")
            # (Line 61) s.fadeIn("\x13\x11당신은 그녀에게 큰 지지대가 되어 주었습니다.", wait=3, line=9);
            s.fadeIn("\x13\x11당신은 그녀에게 큰 지지대가 되어 주었습니다.", wait=3, line=9)
            # (Line 62) }
            # (Line 63) if(fx.timer(768,864)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(768, 864)):
            # (Line 64) s.printAt(0,"\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 65) s.printAt(7, "\x13\x11일기를 통해 알 수 있듯이");
            s.printAt(7, "\x13\x11일기를 통해 알 수 있듯이")
            # (Line 66) s.printAt(8, "\x13\x11당신은 그녀에게 큰 지지대가 되어 주었습니다.");
            s.printAt(8, "\x13\x11당신은 그녀에게 큰 지지대가 되어 주었습니다.")
            # (Line 67) s.fadeIn("\x13\x11그러나 당신이 일 때문에 그녀를 소홀히 했기에", wait=3, line=9);
            s.fadeIn("\x13\x11그러나 당신이 일 때문에 그녀를 소홀히 했기에", wait=3, line=9)
            # (Line 68) }
            # (Line 69) if(fx.timer(864,1008)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(864, 1008)):
            # (Line 70) s.printAt(0,"\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n")
            # (Line 71) s.printAt(6, "\x13\x11일기를 통해 알 수 있듯이");
            s.printAt(6, "\x13\x11일기를 통해 알 수 있듯이")
            # (Line 72) s.printAt(7, "\x13\x11당신은 그녀에게 큰 지지대가 되어 주었습니다.");
            s.printAt(7, "\x13\x11당신은 그녀에게 큰 지지대가 되어 주었습니다.")
            # (Line 73) s.printAt(8, "\x13\x11그러나 당신이 일 때문에 그녀를 소홀히 했기에");
            s.printAt(8, "\x13\x11그러나 당신이 일 때문에 그녀를 소홀히 했기에")
            # (Line 74) s.fadeIn("\x13\x11그녀의 마지막 \x15울타리\x11도 무너지고 말았죠.", wait=4, line=9);
            s.fadeIn("\x13\x11그녀의 마지막 \x15울타리\x11도 무너지고 말았죠.", wait=4, line=9)
            # (Line 75) }
            # (Line 77) if(fx.timer(1008,1140)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1008, 1140)):
            # (Line 78) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 79) s.fadeIn("\x13\x11당신은 충분히 이 \x1C사실\x11을 알고 있었을 것입니다.", wait=3, line=9);
            s.fadeIn("\x13\x11당신은 충분히 이 \x1C사실\x11을 알고 있었을 것입니다.", wait=3, line=9)
            # (Line 80) }
            # (Line 82) if(fx.timer(1140, 1224)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1140, 1224)):
            # (Line 83) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 84) s.printAt(9, "\x13\x04그렇지만... 나는 몰랐어...");
            s.printAt(9, "\x13\x04그렇지만... 나는 몰랐어...")
            # (Line 85) }
            # (Line 87) if(fx.timer(1224,1320)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1224, 1320)):
            # (Line 88) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 89) s.printAt(9, "\x13\x11모르셨다구요?");
            s.printAt(9, "\x13\x11모르셨다구요?")
            # (Line 90) }
            # (Line 92) if(fx.timer(1320,1440)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1320, 1440)):
            # (Line 93) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 94) s.fadeIn("\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.",wait=3, line=9);
            s.fadeIn("\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.", wait=3, line=9)
            # (Line 95) }
            # (Line 96) if(fx.timer(1440,1560)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1440, 1560)):
            # (Line 97) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 98) s.printAt(8, "\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.");
            s.printAt(8, "\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.")
            # (Line 99) s.fadeIn("\x13\x11당신이 \x03그녀\x11와 만난 \x1F3년\x11동안 당신이 받았던 \x08사랑\x11과",wait=3, line=9);
            s.fadeIn("\x13\x11당신이 \x03그녀\x11와 만난 \x1F3년\x11동안 당신이 받았던 \x08사랑\x11과", wait=3, line=9)
            # (Line 100) }
            # (Line 101) if(fx.timer(1560,1680)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1560, 1680)):
            # (Line 102) s.printAt(0,"\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 103) s.printAt(7, "\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.");
            s.printAt(7, "\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.")
            # (Line 104) s.printAt(8, "\x13\x11당신이 \x03그녀\x11와 만난 \x1F3년\x11동안 당신이 받았던 \x08사랑\x11과");
            s.printAt(8, "\x13\x11당신이 \x03그녀\x11와 만난 \x1F3년\x11동안 당신이 받았던 \x08사랑\x11과")
            # (Line 105) s.fadeIn("\x13\x11당신이 주었던 \x08사랑\x11을 비교해 보세요.", wait=3, line=9);
            s.fadeIn("\x13\x11당신이 주었던 \x08사랑\x11을 비교해 보세요.", wait=3, line=9)
            # (Line 106) }
            # (Line 107) if(fx.timer(1680,1800)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1680, 1800)):
            # (Line 108) s.printAt(0,"\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n")
            # (Line 109) s.printAt(6, "\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.");
            s.printAt(6, "\x13\x11그동안 당신이 받아왔던 \x04편지\x11를 생각해 보세요.")
            # (Line 110) s.printAt(7, "\x13\x11당신이 \x03그녀\x11와 만난 \x1F3년\x11동안 당신이 받았던 \x08사랑\x11과");
            s.printAt(7, "\x13\x11당신이 \x03그녀\x11와 만난 \x1F3년\x11동안 당신이 받았던 \x08사랑\x11과")
            # (Line 111) s.printAt(8, "\x13\x11당신이 주었던 \x08사랑\x11을 비교해 보세요.");
            s.printAt(8, "\x13\x11당신이 주었던 \x08사랑\x11을 비교해 보세요.")
            # (Line 112) s.fadeIn("\x13\x11아직도 그녀가 얼마나 당신을 사랑했는지 모르시겠습니까?",wait=2, line=9);
            s.fadeIn("\x13\x11아직도 그녀가 얼마나 당신을 사랑했는지 모르시겠습니까?", wait=2, line=9)
            # (Line 113) }
            # (Line 115) if(fx.timer(1800,1920)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1800, 1920)):
            # (Line 116) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 117) s.fadeIn("\x13\x11당신에게 선택의 기회를 드리겠습니다.", wait=4, line=9);
            s.fadeIn("\x13\x11당신에게 선택의 기회를 드리겠습니다.", wait=4, line=9)
            # (Line 118) }
            # (Line 120) if(fx.timer(1920, 2016)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(1920, 2016)):
            # (Line 121) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 122) s.printAt(9, "\x13\x11이것은 \x08독당근\x11입니다.");
            s.printAt(9, "\x13\x11이것은 \x08독당근\x11입니다.")
            # (Line 123) }
            # (Line 125) if(fx.timer(2016, 2112)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2016, 2112)):
            # (Line 126) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 127) s.printAt(9, "\x13\x11이것을 먹으면 당신은 죽게 되지만");
            s.printAt(9, "\x13\x11이것을 먹으면 당신은 죽게 되지만")
            # (Line 128) }
            # (Line 130) if(fx.timer(2112,2232)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2112, 2232)):
            # (Line 131) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 132) s.fadeIn("\x13\x03Geranium\x11은 다시 살아올 수 있게 됩니다.", wait=3, line=9);
            s.fadeIn("\x13\x03Geranium\x11은 다시 살아올 수 있게 됩니다.", wait=3, line=9)
            # (Line 133) }
            # (Line 135) if(fx.timer(2232,2352)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2232, 2352)):
            # (Line 136) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 137) s.fadeIn("\x13\x11그녀에게 할 수 있는 마지막 \x08사랑\x11입니다.", wait=3, line=9);
            s.fadeIn("\x13\x11그녀에게 할 수 있는 마지막 \x08사랑\x11입니다.", wait=3, line=9)
            # (Line 138) }
            # (Line 140) if(fx.timer(2352,2472)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2352, 2472)):
            # (Line 141) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 142) s.fadeIn("\x13\x05어떻게 하시겠습니까?", wait=8, line=9);
            s.fadeIn("\x13\x05어떻게 하시겠습니까?", wait=8, line=9)
            # (Line 143) }
            # (Line 145) if(fx.timer(2472, 2592)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2472, 2592)):
            # (Line 146) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 147) s.fadeIn("\x13\x04 ......", wait=8, line=9);
            s.fadeIn("\x13\x04 ......", wait=8, line=9)
            # (Line 148) }
            # (Line 150) if(fx.timer(2592, 2712)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2592, 2712)):
            # (Line 151) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 152) s.fadeIn("\x13\x04 먹 겠 습 니 다.", wait=4, line=9);
            s.fadeIn("\x13\x04 먹 겠 습 니 다.", wait=4, line=9)
            # (Line 153) }
            # (Line 155) if(fx.timer(2712, 3000)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2712, 3000)):
            # (Line 156) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 157) }
            # (Line 159) if(fx.timer(2900, 2996)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2900, 2996)):
            # (Line 160) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 161) s.fadeIn("\x13\x04 ......", wait=6, line=9);
            s.fadeIn("\x13\x04 ......", wait=6, line=9)
            # (Line 162) }
            # (Line 164) if(fx.timer(2996, 3126)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(2996, 3126)):
            # (Line 165) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 166) s.fadeIn("\x13\x04 꿈이었나...?", wait=6, line=9);
            s.fadeIn("\x13\x04 꿈이었나...?", wait=6, line=9)
            # (Line 167) }
            # (Line 169) if(fx.timer(3126,3200)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(3126, 3200)):
            # (Line 170) s.print("\n\n\x13\x04달\t력\n\n\x13\x042039년 3월 11일\n\n\n\n\n\n\n");
            s.print("\n\n\x13\x04달\t력\n\n\x13\x042039년 3월 11일\n\n\n\n\n\n\n")
            # (Line 171) }
            # (Line 173) if(fx.timer(3200,3400)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(3200, 3400)):
            # (Line 174) s.printAt(0, "\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 175) if(!s.fadeIn("\x13\x04그렇다면 내일은 \x03Geranium\x04과 만나고 난 후", wait=4, line=8)) {
            if EUDIf()(s.fadeIn("\x13\x04그렇다면 내일은 \x03Geranium\x04과 만나고 난 후", wait=4, line=8), neg=True):
                # (Line 176) s.fadeIn("\x13\x04그녀의 첫 생일이군.", wait=4, line=9);
                s.fadeIn("\x13\x04그녀의 첫 생일이군.", wait=4, line=9)
                # (Line 177) }
                # (Line 178) }
            EUDEndIf()
            # (Line 180) if(fx.timer(3400,3520)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(3400, 3520)):
            # (Line 181) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 182) s.fadeIn("\x13\x04이번에는 반드시...", wait=4, line=9);
            s.fadeIn("\x13\x04이번에는 반드시...", wait=4, line=9)
            # (Line 183) }
            # (Line 185) if(fx.timer(3520,3600)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(3520, 3600)):
            # (Line 186) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 187) s.fadeIn("\x13\x04반드시", wait=4, line=9);
            s.fadeIn("\x13\x04반드시", wait=4, line=9)
            # (Line 188) }
            # (Line 190) if(fx.timer(3600,3720)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(3600, 3720)):
            # (Line 191) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 192) s.fadeIn("\x13\x08사랑\x04해줄게", wait=4, line=9);
            s.fadeIn("\x13\x08사랑\x04해줄게", wait=4, line=9)
            # (Line 193) }
            # (Line 195) if(fx.timer(3720,3800)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(3720, 3800)):
            # (Line 196) fx.time_reset();
            fx.f_time_reset()
            # (Line 197) fx.Chapter_change(9);
            fx.Chapter_change(9)
            # (Line 198) }
            # (Line 199) }
        EUDEndIf()
        # (Line 200) }

    # (Line 202) function EndingCredit() {

@EUDFunc
def EndingCredit():
    # (Line 203) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 204) foreach(cp : EUDLoopPlayer("Human")) {
    for cp in EUDLoopPlayer("Human"):
        # (Line 205) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 206) CenterView("Story");
        # (Line 207) if(fx.timer(100,260)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_timer(100, 260)):
            # (Line 208) s.print("\n\n\n\x13\x07플레이 \x04해주셔서 감사합니다!\n\n\n\x13\x04무심코 놓치고 있었던 주변이들에게 \x08사랑\x04을 표현해보는 건 어떨까요?\n\n\n\n\n");
            s.print("\n\n\n\x13\x07플레이 \x04해주셔서 감사합니다!\n\n\n\x13\x04무심코 놓치고 있었던 주변이들에게 \x08사랑\x04을 표현해보는 건 어떨까요?\n\n\n\n\n")
            # (Line 209) }
            # (Line 210) if(fx.timer(260,740)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(260, 740)):
            # (Line 211) s.print("\x13\x04비록 저의 첫 자작 맵이지만\n\n\x13\x04즐겁게 즐겨주셨으면 하는 마음입니다.\n\x13\x04다운로드 받았던 글에 지금 현재 화면을 \x1F스샷\x04하셔서 올려주시고\n\x13\x04양식에 맞추어 저에게 연락해주시면 됩니다\n\n\x12\x08S\x04pecial \x07T\x04hanks to:\n\n\x12\x11W\x04oozoo(Story Advisor)\n\x12\x08A\x04vlos(Engineering)\n\x12\x07c\x04om''(Engineering)");
            s.print("\x13\x04비록 저의 첫 자작 맵이지만\n\n\x13\x04즐겁게 즐겨주셨으면 하는 마음입니다.\n\x13\x04다운로드 받았던 글에 지금 현재 화면을 \x1F스샷\x04하셔서 올려주시고\n\x13\x04양식에 맞추어 저에게 연락해주시면 됩니다\n\n\x12\x08S\x04pecial \x07T\x04hanks to:\n\n\x12\x11W\x04oozoo(Story Advisor)\n\x12\x08A\x04vlos(Engineering)\n\x12\x07c\x04om''(Engineering)")
            # (Line 212) }
            # (Line 213) if(fx.timer(740,980)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(740, 980)):
            # (Line 214) s.print("\n\n\x13\x04[미궁] \x1DMyosotis\n\n\n\n\n\n\x12\x0EO\x04p \x07K\x04iyoN-\n\x12\x04Mady By \x08K\x04iyoN.\x11C\x04hocochip\n\x12\x04제작기간 2021.06.05~2021.06.08\n");
            s.print("\n\n\x13\x04[미궁] \x1DMyosotis\n\n\n\n\n\n\x12\x0EO\x04p \x07K\x04iyoN-\n\x12\x04Mady By \x08K\x04iyoN.\x11C\x04hocochip\n\x12\x04제작기간 2021.06.05~2021.06.08\n")
            # (Line 215) }
            # (Line 216) if(fx.timer(980,1000)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(980, 1000)):
            # (Line 217) Victory();
            # (Line 218) }
            DoActions(Victory())
            # (Line 219) }
        EUDEndIf()
        # (Line 220) }
