## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import functions as fx;
import functions as fx
# (Line 3) const s = StringBuffer(1024);
s = _CGFW(lambda: [StringBuffer(1024)], 1)[0]
# (Line 5) function Chapter1() {
@EUDFunc
def Chapter1():
    # (Line 6) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 7) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 8) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 9) CenterView("Story");
        # (Line 11) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 12) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 13) }
            # (Line 15) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 16) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 17) }
            # (Line 19) if(fx.timer(0,24)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(0, 24)):
            # (Line 20) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 21) }
            # (Line 22) if(fx.timer(24,72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(24, 72)):
            # (Line 23) s.printAt(0,"\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 24) }
            # (Line 26) if(fx.timer(72,384)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 384)):
            # (Line 27) s.printAt(0, "\n\n");
            s.printAt(0, "\n\n")
            # (Line 28) s.fadeIn("2041년 3월 15일", wait=6, line=2);
            s.fadeIn("2041년 3월 15일", wait=6, line=2)
            # (Line 29) }
            # (Line 31) if(fx.timer(72, 168)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 168)):
            # (Line 32) s.printAt(3, "\n\n\n\n\n\n");
            s.printAt(3, "\n\n\n\n\n\n")
            # (Line 33) }
            # (Line 35) if(fx.timer(168, 384)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(168, 384)):
            # (Line 36) s.printAt(3, "\n\n\n\n\n\n");
            s.printAt(3, "\n\n\n\n\n\n")
            # (Line 37) s.printAt(7, "\x04\x13어제 나의 탐정사무소로 한 쪽지가 도착했다.");
            s.printAt(7, "\x04\x13어제 나의 탐정사무소로 한 쪽지가 도착했다.")
            # (Line 38) }
            # (Line 40) if(fx.timer(240, 384)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(240, 384)):
            # (Line 41) s.printAt(8, "\x04\x13그 쪽지에는 \x03그녀\x04의 \x08사망\x04소식이 적혀 있었고,");
            s.printAt(8, "\x04\x13그 쪽지에는 \x03그녀\x04의 \x08사망\x04소식이 적혀 있었고,")
            # (Line 42) }
            # (Line 44) if(fx.timer(312, 384)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(312, 384)):
            # (Line 45) s.printAt(9, "\x04\x13나는 사실을 파헤치기 위해 \x03그녀\x04의 집으로 향했다.");
            s.printAt(9, "\x04\x13나는 사실을 파헤치기 위해 \x03그녀\x04의 집으로 향했다.")
            # (Line 46) }
            # (Line 48) if(fx.timer(384, 388)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(384, 388)):
            # (Line 49) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 50) s.printAt(7, "\x05\x13어제 나의 탐정사무소로 한 쪽지가 도착했다.");
            s.printAt(7, "\x05\x13어제 나의 탐정사무소로 한 쪽지가 도착했다.")
            # (Line 51) s.printAt(8, "\x05\x13그 쪽지에는 그녀의 사망소식이 적혀 있었고,");
            s.printAt(8, "\x05\x13그 쪽지에는 그녀의 사망소식이 적혀 있었고,")
            # (Line 52) s.printAt(9, "\x05\x13나는 사실을 파헤치기 위해 그녀의 집으로 향했다.");
            s.printAt(9, "\x05\x13나는 사실을 파헤치기 위해 그녀의 집으로 향했다.")
            # (Line 53) }
            # (Line 55) if(fx.timer(388, 432)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(388, 432)):
            # (Line 56) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 57) }
            # (Line 59) if(fx.timer(432, 528)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(432, 528)):
            # (Line 60) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 61) s.printAt(9, "\x05\x13그녀\x01가 없는 집은 공허함만이 존재했다.");
            s.printAt(9, "\x05\x13그녀\x01가 없는 집은 공허함만이 존재했다.")
            # (Line 62) }
            # (Line 64) if(fx.timer(528, 624)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(528, 624)):
            # (Line 65) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 66) s.printAt(9, "\x03\x13그녀\x04의 집을 돌아보던 중, \x03그녀\x04의 일기장을 발견했다.");
            s.printAt(9, "\x03\x13그녀\x04의 집을 돌아보던 중, \x03그녀\x04의 일기장을 발견했다.")
            # (Line 67) }
            # (Line 69) if(fx.timer(624, 808)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(624, 808)):
            # (Line 70) s.printAt(0, "\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n")
            # (Line 71) s.printAt(8, "\x04\x13그 일기장은 2041년 1월 30일부터 하루도 빠짐없이 적혀있었다.");
            s.printAt(8, "\x04\x13그 일기장은 2041년 1월 30일부터 하루도 빠짐없이 적혀있었다.")
            # (Line 72) s.printAt(9, "\n");
            s.printAt(9, "\n")
            # (Line 73) }
            # (Line 75) if(fx.timer(716, 808)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(716, 808)):
            # (Line 76) s.printAt(9, "\x04\x13비교적 최근 것부터 읽어보기로 했다.");
            s.printAt(9, "\x04\x13비교적 최근 것부터 읽어보기로 했다.")
            # (Line 77) }
            # (Line 79) if(fx.timer(808,832)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(808, 832)):
            # (Line 80) CenterView("Answer");
            # (Line 81) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 82) fx.Chapter_change(11);
            fx.Chapter_change(11)
            # (Line 83) }
            # (Line 84) }
        EUDEndIf()
        # (Line 85) }

    # (Line 87) function Chapter2() {

@EUDFunc
def Chapter2():
    # (Line 88) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 89) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 90) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 91) CenterView("Story");
        # (Line 93) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 94) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 95) }
            # (Line 97) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 98) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 99) }
            # (Line 101) if(fx.timer(60, 72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(60, 72)):
            # (Line 102) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 103) }
            # (Line 105) if(fx.timer(72, 216)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 216)):
            # (Line 106) s.printAt(0, "\x043월 8일 월요일 (2/2)");
            s.printAt(0, "\x043월 8일 월요일 (2/2)")
            # (Line 107) s.printAt(1, "\n\n\n\n\n\n\n");
            s.printAt(1, "\n\n\n\n\n\n\n")
            # (Line 108) s.printAt(8, "그 안에는 \x15밤꽃\x02이 들어있었다.");
            s.printAt(8, "그 안에는 \x15밤꽃\x02이 들어있었다.")
            # (Line 109) }
            # (Line 111) if(fx.timer(144, 216)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(144, 216)):
            # (Line 112) s.printAt(9, "그 어느때보다 그의 \x11진심\x02을 느낄 수 있었다.");
            s.printAt(9, "그 어느때보다 그의 \x11진심\x02을 느낄 수 있었다.")
            # (Line 113) }
            # (Line 115) if(fx.timer(216, 220)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(216, 220)):
            # (Line 116) s.print("\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n")
            # (Line 117) }
            # (Line 119) if(fx.timer(220, 288)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(220, 288)):
            # (Line 120) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 121) s.printAt(9, "\x13\x04(다음 페이지로 넘긴다)");
            s.printAt(9, "\x13\x04(다음 페이지로 넘긴다)")
            # (Line 122) }
            # (Line 124) if(fx.timer(288, 300)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(288, 300)):
            # (Line 125) CenterView("Answer");
            # (Line 126) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 127) fx.Chapter_change(12);
            fx.Chapter_change(12)
            # (Line 128) }
            # (Line 129) }
        EUDEndIf()
        # (Line 130) }

    # (Line 132) function Chapter3() {

@EUDFunc
def Chapter3():
    # (Line 133) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 134) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 135) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 136) CenterView("Story");
        # (Line 138) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 139) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 140) }
            # (Line 142) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 143) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 144) }
            # (Line 146) if(fx.timer(60,72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(60, 72)):
            # (Line 147) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 148) }
            # (Line 150) if(fx.timer(72, 144)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 144)):
            # (Line 151) s.printAt(0, "\x043월 9일 화요일 (3/3)");
            s.printAt(0, "\x043월 9일 화요일 (3/3)")
            # (Line 152) s.printAt(1, "\n\n\n\n\n\n\n\n");
            s.printAt(1, "\n\n\n\n\n\n\n\n")
            # (Line 153) s.printAt(9, "그 안에는 시간이 지나 말라버린 \x18낙엽송\x02의 열매가 들어 있었다.");
            s.printAt(9, "그 안에는 시간이 지나 말라버린 \x18낙엽송\x02의 열매가 들어 있었다.")
            # (Line 154) }
            # (Line 156) if(fx.timer(144,168)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(144, 168)):
            # (Line 157) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 158) }
            # (Line 160) if(fx.timer(168, 240)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(168, 240)):
            # (Line 161) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 162) s.printAt(9, "\x13\x04나는 계속해서 일기장을 읽어 내려갔다.");
            s.printAt(9, "\x13\x04나는 계속해서 일기장을 읽어 내려갔다.")
            # (Line 163) }
            # (Line 165) if(fx.timer(240,260)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(240, 260)):
            # (Line 166) CenterView("Answer");
            # (Line 167) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 168) fx.Chapter_change(13);
            fx.Chapter_change(13)
            # (Line 169) }
            # (Line 170) }
        EUDEndIf()
        # (Line 171) }

    # (Line 173) function Chapter4() {

@EUDFunc
def Chapter4():
    # (Line 174) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 175) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 176) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 177) CenterView("Story");
        # (Line 179) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 180) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 181) }
            # (Line 183) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 184) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 185) }
            # (Line 187) if(fx.timer(60,72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(60, 72)):
            # (Line 188) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 189) }
            # (Line 191) if(fx.timer(72, 192)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 192)):
            # (Line 192) s.printAt(0, "\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n")
            # (Line 193) s.printAt(8, "\x13\x04그 후 나는 식탁에서");
            s.printAt(8, "\x13\x04그 후 나는 식탁에서")
            # (Line 194) }
            # (Line 196) if(fx.timer(120, 192)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(120, 192)):
            # (Line 197) s.printAt(9, "\x13\x04텅 비어버린 \x08수면제 통\x04을 발견할 수 있었다.");
            s.printAt(9, "\x13\x04텅 비어버린 \x08수면제 통\x04을 발견할 수 있었다.")
            # (Line 198) }
            # (Line 200) if(fx.timer(192,230)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(192, 230)):
            # (Line 201) CenterView("Answer");
            # (Line 202) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 203) fx.Chapter_change(14);
            fx.Chapter_change(14)
            # (Line 204) }
            # (Line 205) }
        EUDEndIf()
        # (Line 206) }

    # (Line 208) function Chapter5() {

@EUDFunc
def Chapter5():
    # (Line 209) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 210) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 211) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 212) CenterView("Story");
        # (Line 214) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 215) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 216) }
            # (Line 218) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 219) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 220) }
            # (Line 222) if(fx.timer(60,72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(60, 72)):
            # (Line 223) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 224) }
            # (Line 226) if(fx.timer(72,168)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 168)):
            # (Line 227) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 228) s.printAt(9, "\x13\x04난 그저 아무말 없이 읽어내려갔다.");
            s.printAt(9, "\x13\x04난 그저 아무말 없이 읽어내려갔다.")
            # (Line 229) }
            # (Line 231) if(fx.timer(168, 190)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(168, 190)):
            # (Line 232) CenterView("Answer");
            # (Line 233) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 234) fx.Chapter_change(15);
            fx.Chapter_change(15)
            # (Line 235) }
            # (Line 236) }
        EUDEndIf()
        # (Line 237) }

    # (Line 239) function Chapter6() {

@EUDFunc
def Chapter6():
    # (Line 240) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 241) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 242) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 243) CenterView("Story");
        # (Line 245) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 246) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 247) }
            # (Line 249) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 250) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 251) }
            # (Line 253) if(fx.timer(60,72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(60, 72)):
            # (Line 254) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 255) }
            # (Line 257) if(fx.timer(72, 168)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 168)):
            # (Line 258) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 259) s.fadeIn("\x13\x04......", wait=6, line=9);
            s.fadeIn("\x13\x04......", wait=6, line=9)
            # (Line 260) }
            # (Line 262) if(fx.timer(168,172)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(168, 172)):
            # (Line 263) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 264) s.printAt(9, "\x13\x05......");
            s.printAt(9, "\x13\x05......")
            # (Line 265) }
            # (Line 267) if(fx.timer(172,176)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(172, 176)):
            # (Line 268) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 269) }
            # (Line 271) if(fx.timer(176, 200)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(176, 200)):
            # (Line 272) CenterView("Answer");
            # (Line 273) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 274) fx.Chapter_change(16);
            fx.Chapter_change(16)
            # (Line 275) }
            # (Line 276) }
        EUDEndIf()
        # (Line 277) }

    # (Line 279) function Chapter7() {

@EUDFunc
def Chapter7():
    # (Line 280) fx.set_BG(0);
    fx.f_set_BG(0)
    # (Line 281) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 282) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 283) CenterView("Story");
        # (Line 285) if(fx.off_bgm(cp)) {
        DoActions(CenterView("Story"))
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 286) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 287) }
            # (Line 289) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 290) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 291) }
            # (Line 293) if(fx.timer(60,72)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(60, 72)):
            # (Line 294) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 295) }
            # (Line 297) if(fx.timer(72, 168)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(72, 168)):
            # (Line 298) s.printAt(0, "\n\n\n\n\n\n\n\n\n");
            s.printAt(0, "\n\n\n\n\n\n\n\n\n")
            # (Line 299) s.fadeIn("\x13\x04그렇다면... 설마...?", wait=4, line=9);
            s.fadeIn("\x13\x04그렇다면... 설마...?", wait=4, line=9)
            # (Line 300) }
            # (Line 302) if(fx.timer(168,172)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(168, 172)):
            # (Line 303) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 304) }
            # (Line 306) if(fx.timer(172,200)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(172, 200)):
            # (Line 307) CenterView("Answer");
            # (Line 308) fx.time_reset();
            DoActions(CenterView("Answer"))
            fx.f_time_reset()
            # (Line 309) fx.Chapter_change(17);
            fx.Chapter_change(17)
            # (Line 310) }
            # (Line 311) }
        EUDEndIf()
        # (Line 312) }
