## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import functions as fx;
import functions as fx
# (Line 3) const s = StringBuffer(1024);
s = _CGFW(lambda: [StringBuffer(1024)], 1)[0]
# (Line 5) function Question1() {
@EUDFunc
def Question1():
    # (Line 6) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 7) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 8) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 9) if(fx.timer(0,240)) {
        if EUDIf()(fx.f_timer(0, 240)):
            # (Line 10) s.print("\x13이 미궁의 답은 모두 \x08영어\x02로만 되어 있습니다.\n\n\x13답이 4글자 이상일 경우 \x04앞의 4글자\x02가 정답이 됩니다.\n\n\x13\x07Ex) Myosotis → myos\n\n\x13답이 4글자 미만으로 남는 시민이 있는 경우에는 \x1DUnused\x02칸으로 가시면 됩니다.\n\n\x13브금은 \x1FDelete\x02키로 끌 수 있으며, \x1CInsert\x02키로 다시 키실 수 있습니다.\n\n\n");
            s.print("\x13이 미궁의 답은 모두 \x08영어\x02로만 되어 있습니다.\n\n\x13답이 4글자 이상일 경우 \x04앞의 4글자\x02가 정답이 됩니다.\n\n\x13\x07Ex) Myosotis → myos\n\n\x13답이 4글자 미만으로 남는 시민이 있는 경우에는 \x1DUnused\x02칸으로 가시면 됩니다.\n\n\x13브금은 \x1FDelete\x02키로 끌 수 있으며, \x1CInsert\x02키로 다시 키실 수 있습니다.\n\n\n")
            # (Line 11) }
            # (Line 12) if(fx.timer(240,432)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(240, 432)):
            # (Line 13) s.print("\x13모든 문제는 \x1F일기장\x02을 기반으로 나오며\n\n\x13\x1B\"Z\"\x02키를 누를시 1페이지, \x11\"X\"\x02를 누를시 2페이지가 나옵니다.\n\n\x13일기장의 내용을 읽고 \x1C답\x02을 도출해 내시면 됩니다.\n\n\n\x13이 미궁은 스토리가 \x08큰 비중\x02을 차지합니다.\n\n\n\x13그럼 \x03행운\x02을 빌겠습니다\n");
            s.print("\x13모든 문제는 \x1F일기장\x02을 기반으로 나오며\n\n\x13\x1B\"Z\"\x02키를 누를시 1페이지, \x11\"X\"\x02를 누를시 2페이지가 나옵니다.\n\n\x13일기장의 내용을 읽고 \x1C답\x02을 도출해 내시면 됩니다.\n\n\n\x13이 미궁은 스토리가 \x08큰 비중\x02을 차지합니다.\n\n\n\x13그럼 \x03행운\x02을 빌겠습니다\n")
            # (Line 14) }
            # (Line 15) if(fx.timer(432,436)) {
        EUDEndIf()
        if EUDIf()(fx.f_timer(432, 436)):
            # (Line 16) s.print("\n\n\n\n\n\n\n\n\n\n\n");
            s.print("\n\n\n\n\n\n\n\n\n\n\n")
            # (Line 17) }
            # (Line 19) if(fx.off_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 20) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 21) }
            # (Line 23) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 24) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 25) }
            # (Line 27) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 28) s.print("\x043월 8일 월요일 (1/2)\n\n\n\x02그와 사귄지도 벌써 \x183\x02년이다.\n그가 했던 모든 행동은 그동안 외로웠던 나에게 \x1F울타리\x02가 되어 주었다.\n그러나 요즘은 나보다 일이 먼저인건지 \x04편지\x02를 보내도 답이 없을 때가 많다.\n그래도 답신에는 항상 미안하다며 \x04편지\x02와 \x10선물\x02을 보낸다.\n선물에는 항상 \x15자물쇠\x02가 걸려 있지만\n단서를 보며 풀때면 정말 그 답다고 생각된다.\n\n\n");
            s.print("\x043월 8일 월요일 (1/2)\n\n\n\x02그와 사귄지도 벌써 \x183\x02년이다.\n그가 했던 모든 행동은 그동안 외로웠던 나에게 \x1F울타리\x02가 되어 주었다.\n그러나 요즘은 나보다 일이 먼저인건지 \x04편지\x02를 보내도 답이 없을 때가 많다.\n그래도 답신에는 항상 미안하다며 \x04편지\x02와 \x10선물\x02을 보낸다.\n선물에는 항상 \x15자물쇠\x02가 걸려 있지만\n단서를 보며 풀때면 정말 그 답다고 생각된다.\n\n\n")
            # (Line 29) }
            # (Line 31) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 32) s.print("\x04-편지지-\n\n\n\x04벌써 \x1C3월\x04이오.\n\x06부러진 가위 한쪽\x04이 다른 한짝을 만나고서야\n\x04진정한 역할을 하듯이\n\x04당신과 함께 있어야 나도 존재할 수 있소.\n\x04나도 당신의 곁에 항상 있고 싶소. 사랑하오.\n\n\n\x1FGHWHFWLYH ");
            s.print("\x04-편지지-\n\n\n\x04벌써 \x1C3월\x04이오.\n\x06부러진 가위 한쪽\x04이 다른 한짝을 만나고서야\n\x04진정한 역할을 하듯이\n\x04당신과 함께 있어야 나도 존재할 수 있소.\n\x04나도 당신의 곁에 항상 있고 싶소. 사랑하오.\n\n\n\x1FGHWHFWLYH ")
            # (Line 33) }
            # (Line 35) if(Bring(Force1, Exactly, 1, "Terran Civilian", "1-1") &&
        EUDEndIf()
        _t8 = EUDIf()
        # (Line 36) Bring(Force1, Exactly, 2, "Terran Civilian", "1-2") &&
        # (Line 37) Bring(Force1, Exactly, 1, "Terran Civilian", "1-3")) {
        if _t8(EUDSCAnd()(Bring(Force1, Exactly, 1, "Terran Civilian", "1-1"))(Bring(Force1, Exactly, 2, "Terran Civilian", "1-2"))(Bring(Force1, Exactly, 1, "Terran Civilian", "1-3"))()):
            # (Line 38) fx.time_reset();
            fx.f_time_reset()
            # (Line 39) fx.Chapter_change(2);
            fx.Chapter_change(2)
            # (Line 40) }
            # (Line 41) }
        EUDEndIf()
        # (Line 42) }

    # (Line 44) function Question2() {

@EUDFunc
def Question2():
    # (Line 45) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 46) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 47) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 49) if(fx.off_bgm(cp)) {
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 50) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 51) }
            # (Line 53) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 54) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 55) }
            # (Line 57) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 58) s.print("\x043월 9일 화요일 (1/3)\n\n\n\n\x02혼자 살게 된지 어언 \x078년\x02째.\n\n오늘은 부모님의 기일이다.\n부모님은 \x08불의의 사고\x02로 세상을 떠나셨다.\n\n그렇지만 나에게 \x1F대담\x02해 지라고 하신 말씀만큼은 항상 기억하고 있다.\n\n");
            s.print("\x043월 9일 화요일 (1/3)\n\n\n\n\x02혼자 살게 된지 어언 \x078년\x02째.\n\n오늘은 부모님의 기일이다.\n부모님은 \x08불의의 사고\x02로 세상을 떠나셨다.\n\n그렇지만 나에게 \x1F대담\x02해 지라고 하신 말씀만큼은 항상 기억하고 있다.\n\n")
            # (Line 59) }
            # (Line 61) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 62) s.print("\x043월 9일 화요일 (2/3)\n\n\x02비지..네..르? 라고 적혀있는 것 같다.\n아버지께서 남겨두신 유품이다.\n쪽지에는 이렇게 적혀있었다.\n\n\x04-쪽지-\n\n\x03대담\x04해지거라. \n\n\x1FNHVTPDH\x02");
            s.print("\x043월 9일 화요일 (2/3)\n\n\x02비지..네..르? 라고 적혀있는 것 같다.\n아버지께서 남겨두신 유품이다.\n쪽지에는 이렇게 적혀있었다.\n\n\x04-쪽지-\n\n\x03대담\x04해지거라. \n\n\x1FNHVTPDH\x02")
            # (Line 63) }
            # (Line 65) if(Bring(Force1, Exactly, 1, "Terran Civilian", "2-1") &&
        EUDEndIf()
        _t5 = EUDIf()
        # (Line 66) Bring(Force1, Exactly, 1, "Terran Civilian", "2-2") &&
        # (Line 67) Bring(Force1, Exactly, 1, "Terran Civilian", "2-3") &&
        # (Line 68) Bring(Force1, Exactly, 1, "Terran Civilian", "2-4")) {
        if _t5(EUDSCAnd()(Bring(Force1, Exactly, 1, "Terran Civilian", "2-1"))(Bring(Force1, Exactly, 1, "Terran Civilian", "2-2"))(Bring(Force1, Exactly, 1, "Terran Civilian", "2-3"))(Bring(Force1, Exactly, 1, "Terran Civilian", "2-4"))()):
            # (Line 69) fx.Chapter_change(3);
            fx.Chapter_change(3)
            # (Line 70) }
            # (Line 71) }
        EUDEndIf()
        # (Line 72) }

    # (Line 74) function Question3() {

@EUDFunc
def Question3():
    # (Line 75) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 76) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 77) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 79) if(fx.off_bgm(cp)) {
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 80) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 81) }
            # (Line 83) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 84) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 85) }
            # (Line 87) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 88) s.print("\x043월 10일 수요일 (1/2)\n\n\n\n\x02나는 의사에 의해 \x08우울증과 불면증 판정\x02을 받았다.\n이 말을 들은지도 벌써 \x1D4년\x02째다.\n\n중학생 시절 부모님이 돌아가시고\n커다란 벽에 막혀 현실을 마주했을 때 부터인 것 같다.\n점점 약이 강해지고 있다고 한다.\n\n");
            s.print("\x043월 10일 수요일 (1/2)\n\n\n\n\x02나는 의사에 의해 \x08우울증과 불면증 판정\x02을 받았다.\n이 말을 들은지도 벌써 \x1D4년\x02째다.\n\n중학생 시절 부모님이 돌아가시고\n커다란 벽에 막혀 현실을 마주했을 때 부터인 것 같다.\n점점 약이 강해지고 있다고 한다.\n\n")
            # (Line 89) }
            # (Line 91) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 92) s.print("\x043월 10일 수요일 (2/2)\n함\x02 따윈\n\n\x02내 인생에 \x1F고귀 존재 하지 않아.\n\n누군가 나의 선장이 되어 나의 \x08???\x02를 잡아줄 순 없을까?\n\n인생의... 배의 \x08???\x02를 말이야...\n\n내 \x1F고귀함\x02을 감싸 안아주면서...\n\n");
            s.print("\x043월 10일 수요일 (2/2)\n함\x02 따윈\n\n\x02내 인생에 \x1F고귀 존재 하지 않아.\n\n누군가 나의 선장이 되어 나의 \x08???\x02를 잡아줄 순 없을까?\n\n인생의... 배의 \x08???\x02를 말이야...\n\n내 \x1F고귀함\x02을 감싸 안아주면서...\n\n")
            # (Line 93) }
            # (Line 95) if(Bring(Force1, Exactly, 1, "Terran Civilian", "3-1") &&
        EUDEndIf()
        _t5 = EUDIf()
        # (Line 96) Bring(Force1, Exactly, 1, "Terran Civilian", "3-2") &&
        # (Line 97) Bring(Force1, Exactly, 1, "Terran Civilian", "3-3") &&
        # (Line 98) Bring(Force1, Exactly, 1, "Terran Civilian", "3-4")) {
        if _t5(EUDSCAnd()(Bring(Force1, Exactly, 1, "Terran Civilian", "3-1"))(Bring(Force1, Exactly, 1, "Terran Civilian", "3-2"))(Bring(Force1, Exactly, 1, "Terran Civilian", "3-3"))(Bring(Force1, Exactly, 1, "Terran Civilian", "3-4"))()):
            # (Line 99) fx.Chapter_change(4);
            fx.Chapter_change(4)
            # (Line 100) }
            # (Line 101) }
        EUDEndIf()
        # (Line 102) }

    # (Line 104) function Question4() {

@EUDFunc
def Question4():
    # (Line 105) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 106) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 107) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 109) if(fx.off_bgm(cp)) {
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 110) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 111) }
            # (Line 113) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 114) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 115) }
            # (Line 117) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 118) s.print("\x043월 11일 목요일 (1/2)\n\n\x02그를 만난 후 1년간은 내 인생에서 느낄 수 없었던\n가장 큰 \x08사랑\x02을 받았다.\n\n그러나 시간이 지날 수록 그가 나에게서\n멀어져 가고 있다는 생각이 든다.\n\n그를 위해 \x04편지\x02를 쓰지만, 그는 내 \x04편지\x02에 더이상 관심이 없는 것 같다.\n그도 다른 사람들과 같이 \x1D바뀌어 버린 걸까...?\n\n");
            s.print("\x043월 11일 목요일 (1/2)\n\n\x02그를 만난 후 1년간은 내 인생에서 느낄 수 없었던\n가장 큰 \x08사랑\x02을 받았다.\n\n그러나 시간이 지날 수록 그가 나에게서\n멀어져 가고 있다는 생각이 든다.\n\n그를 위해 \x04편지\x02를 쓰지만, 그는 내 \x04편지\x02에 더이상 관심이 없는 것 같다.\n그도 다른 사람들과 같이 \x1D바뀌어 버린 걸까...?\n\n")
            # (Line 119) }
            # (Line 121) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 122) s.print("\x043월 11일 목요일 (2/2)\n\n\n\x02어렸을 땐 \x04순박함\x02으로 포장이라도 됬지,\n\n성인인 지금은 핑계로 밖에 보이지 않을 뿐이야.\n\n비난과 부정적인 시선은 \x18쓴 나물\x02을 먹는 것 같아.\n\n\x08이 나물\x02로 나를 빗댈 수 있을 것 같아.\n\n");
            s.print("\x043월 11일 목요일 (2/2)\n\n\n\x02어렸을 땐 \x04순박함\x02으로 포장이라도 됬지,\n\n성인인 지금은 핑계로 밖에 보이지 않을 뿐이야.\n\n비난과 부정적인 시선은 \x18쓴 나물\x02을 먹는 것 같아.\n\n\x08이 나물\x02로 나를 빗댈 수 있을 것 같아.\n\n")
            # (Line 123) }
            # (Line 125) if(Bring(Force1, Exactly, 1, "Terran Civilian", "4-1") &&
        EUDEndIf()
        _t5 = EUDIf()
        # (Line 126) Bring(Force1, Exactly, 1, "Terran Civilian", "4-2") &&
        # (Line 127) Bring(Force1, Exactly, 1, "Terran Civilian", "4-3") &&
        # (Line 128) Bring(Force1, Exactly, 1, "Terran Civilian", "4-4")) {
        if _t5(EUDSCAnd()(Bring(Force1, Exactly, 1, "Terran Civilian", "4-1"))(Bring(Force1, Exactly, 1, "Terran Civilian", "4-2"))(Bring(Force1, Exactly, 1, "Terran Civilian", "4-3"))(Bring(Force1, Exactly, 1, "Terran Civilian", "4-4"))()):
            # (Line 129) fx.Chapter_change(5);
            fx.Chapter_change(5)
            # (Line 130) }
            # (Line 131) }
        EUDEndIf()
        # (Line 132) }

    # (Line 134) function Question5() {

@EUDFunc
def Question5():
    # (Line 135) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 136) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 137) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 139) if(fx.off_bgm(cp)) {
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 140) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 141) }
            # (Line 143) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 144) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 145) }
            # (Line 147) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 148) s.print("\x043월 12일 금요일 (1/2)\n\n\n\n\x02그에게선 \x08거짓말\x02처럼 아무 말도 없었다.\n얼굴은 고사하고 \x04편지\x02조차. 내 \x03생일\x02인데도 말이다.\n주말인데도, 나를 찾아와 주지 않았다.\n\n이 세상에 내가 기댈 곳은 아무 곳도 없다.\n시간이 지날수록 뼈저리게 느껴진다.\n\n");
            s.print("\x043월 12일 금요일 (1/2)\n\n\n\n\x02그에게선 \x08거짓말\x02처럼 아무 말도 없었다.\n얼굴은 고사하고 \x04편지\x02조차. 내 \x03생일\x02인데도 말이다.\n주말인데도, 나를 찾아와 주지 않았다.\n\n이 세상에 내가 기댈 곳은 아무 곳도 없다.\n시간이 지날수록 뼈저리게 느껴진다.\n\n")
            # (Line 149) }
            # (Line 151) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 152) s.print("\x043월 12일 금요일 (2/2)\n\n\n\x07사랑이 이리도 슬픈\x02 걸까.\n기댔던 내가 바보인걸까?\n\n저 멀리서 \x1C울고 있는 나무\x02도\n나와 같은 상황은 아닐까?\n\n\x15저 나무\x02는 어떤 나무일까...?\n\n");
            s.print("\x043월 12일 금요일 (2/2)\n\n\n\x07사랑이 이리도 슬픈\x02 걸까.\n기댔던 내가 바보인걸까?\n\n저 멀리서 \x1C울고 있는 나무\x02도\n나와 같은 상황은 아닐까?\n\n\x15저 나무\x02는 어떤 나무일까...?\n\n")
            # (Line 153) }
            # (Line 155) if(Bring(Force1, Exactly, 1, "Terran Civilian", "5-1") &&
        EUDEndIf()
        _t5 = EUDIf()
        # (Line 156) Bring(Force1, Exactly, 2, "Terran Civilian", "5-2") &&
        # (Line 157) Bring(Force1, Exactly, 1, "Terran Civilian", "5-3")) {
        if _t5(EUDSCAnd()(Bring(Force1, Exactly, 1, "Terran Civilian", "5-1"))(Bring(Force1, Exactly, 2, "Terran Civilian", "5-2"))(Bring(Force1, Exactly, 1, "Terran Civilian", "5-3"))()):
            # (Line 158) fx.Chapter_change(6);
            fx.Chapter_change(6)
            # (Line 159) }
            # (Line 160) }
        EUDEndIf()
        # (Line 161) }

    # (Line 163) function Question6() {

@EUDFunc
def Question6():
    # (Line 164) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 165) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 166) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 168) if(fx.off_bgm(cp)) {
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 169) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 170) }
            # (Line 172) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 173) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 174) }
            # (Line 176) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 177) s.print("\x043월 13일 토요일 (1/2)\n\n\n\n\x10꽃은 언제나 아름답고,\x07 계절은 시간이 지나도 푸르른데\n\x02내 인생은 점차 나빠지기만 한다...\n더 이상 살 \x1E이유\x02가 있을까?\n\n내게 남은 건 없는데,\n\x08나 하나쯤은 사라져도 괜찮지 않을까?\n\n");
            s.print("\x043월 13일 토요일 (1/2)\n\n\n\n\x10꽃은 언제나 아름답고,\x07 계절은 시간이 지나도 푸르른데\n\x02내 인생은 점차 나빠지기만 한다...\n더 이상 살 \x1E이유\x02가 있을까?\n\n내게 남은 건 없는데,\n\x08나 하나쯤은 사라져도 괜찮지 않을까?\n\n")
            # (Line 178) }
            # (Line 180) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 181) s.print("\x043월 13일 토요일 (2/2)\n\n\n처음 맛본 \x06사랑\x02은 내가 어떤 삶을 살아왔어도\n모든걸 \x11망각\x02 시켜줬어.\n\n하지만 이제는 아니야.\n어떠한 사랑도 그저 나의 단순한 \x1E허상\x02임을\n깨달아 버렸기 때문이야.\n실제로는 \x1D존재하지 않거든.\n\n");
            s.print("\x043월 13일 토요일 (2/2)\n\n\n처음 맛본 \x06사랑\x02은 내가 어떤 삶을 살아왔어도\n모든걸 \x11망각\x02 시켜줬어.\n\n하지만 이제는 아니야.\n어떠한 사랑도 그저 나의 단순한 \x1E허상\x02임을\n깨달아 버렸기 때문이야.\n실제로는 \x1D존재하지 않거든.\n\n")
            # (Line 182) }
            # (Line 184) if(Bring(Force1, Exactly, 4, "Terran Civilian", "6")) {
        EUDEndIf()
        if EUDIf()(Bring(Force1, Exactly, 4, "Terran Civilian", "6")):
            # (Line 185) fx.Chapter_change(7);
            fx.Chapter_change(7)
            # (Line 186) }
            # (Line 187) }
        EUDEndIf()
        # (Line 188) }

    # (Line 190) function Question7() {

@EUDFunc
def Question7():
    # (Line 191) fx.set_BG(31);
    fx.f_set_BG(31)
    # (Line 192) foreach(cp : EUDLoopPlayer()) {
    for cp in EUDLoopPlayer():
        # (Line 193) setcurpl(cp);
        f_setcurpl(cp)
        # (Line 195) if(fx.off_bgm(cp)) {
        if EUDIf()(fx.f_off_bgm(cp)):
            # (Line 196) s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.");
            s.printAt(10, "\x13\x07Ctrl + SS\x02를 눌러 브금을 꺼주세요. \x1DInsert\x02키로 다시 킬 수 있습니다.")
            # (Line 197) }
            # (Line 199) if(fx.on_bgm(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_on_bgm(cp)):
            # (Line 200) s.printAt(10, "\x13브금을 켰습니다.");
            s.printAt(10, "\x13브금을 켰습니다.")
            # (Line 201) }
            # (Line 203) if(fx.press_z(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_z(cp)):
            # (Line 204) s.print("\x043월 14일 일요일\n\n\n\x02내가 죽으면 넌 \x1F이 일기\x02를 읽겠지...\n\n그동안 \x03고마웠어.\n\n\x04아몬드 꽃\x02은 영원히 우리 안에서 지지 않을거야.\n\n너만큼은 \x11행복\x02하길 바랄게...\n\n");
            s.print("\x043월 14일 일요일\n\n\n\x02내가 죽으면 넌 \x1F이 일기\x02를 읽겠지...\n\n그동안 \x03고마웠어.\n\n\x04아몬드 꽃\x02은 영원히 우리 안에서 지지 않을거야.\n\n너만큼은 \x11행복\x02하길 바랄게...\n\n")
            # (Line 205) }
            # (Line 207) if(fx.press_x(cp)) {
        EUDEndIf()
        if EUDIf()(fx.f_press_x(cp)):
            # (Line 208) s.printAt(9, "\x13\x04이 페이지는 비어있다.");
            s.printAt(9, "\x13\x04이 페이지는 비어있다.")
            # (Line 209) }
            # (Line 211) if(Bring(Force1, Exactly, 1, "Terran Civilian", "7-1") &&
        EUDEndIf()
        _t5 = EUDIf()
        # (Line 212) Bring(Force1, Exactly, 1, "Terran Civilian", "7-2") &&
        # (Line 213) Bring(Force1, Exactly, 1, "Terran Civilian", "7-3") &&
        # (Line 214) Bring(Force1, Exactly, 1, "Terran Civilian", "7-4")) {
        if _t5(EUDSCAnd()(Bring(Force1, Exactly, 1, "Terran Civilian", "7-1"))(Bring(Force1, Exactly, 1, "Terran Civilian", "7-2"))(Bring(Force1, Exactly, 1, "Terran Civilian", "7-3"))(Bring(Force1, Exactly, 1, "Terran Civilian", "7-4"))()):
            # (Line 215) fx.Chapter_change(8);
            fx.Chapter_change(8)
            # (Line 216) }
            # (Line 217) }
        EUDEndIf()
        # (Line 218) }
