## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 6) var readMode		= 1; //0이면 작동안함, 1이면 작동함
readMode = EUDCreateVariables(1)
_IGVA([readMode], lambda: [1])
# (Line 7) var screenGridX		= 0; //화면 X좌표 (비공유)
screenGridX = EUDCreateVariables(1)
_IGVA([screenGridX], lambda: [0])
# (Line 8) var screenGridY		= 0; //화면 Y좌표 (비공유)
screenGridY = EUDCreateVariables(1)
_IGVA([screenGridY], lambda: [0])
# (Line 9) var screenSizeX		= 0; //화면X축 크기 (비공유)
screenSizeX = EUDCreateVariables(1)
_IGVA([screenSizeX], lambda: [0])
# (Line 10) var screenSizeY		= 0; //화면Y축 크기 (비공유)
screenSizeY = EUDCreateVariables(1)
_IGVA([screenSizeY], lambda: [0])
# (Line 11) var mouseX			= 0; //마우스 상대좌표X (비공유)
mouseX = EUDCreateVariables(1)
_IGVA([mouseX], lambda: [0])
# (Line 12) var mouseY			= 0; //마우스 상대좌표Y (비공유)
mouseY = EUDCreateVariables(1)
_IGVA([mouseY], lambda: [0])
# (Line 13) const mouseMX		= EPD(0x6CDDC4); //마우스 상대좌표X 오프셋
mouseMX = _CGFW(lambda: [EPD(0x6CDDC4)], 1)[0]
# (Line 14) const mouseMY		= EPD(0x6CDDC8); //마우스 상대좌표Y 오프셋
mouseMY = _CGFW(lambda: [EPD(0x6CDDC8)], 1)[0]
# (Line 16) const mouseClick	= PVariable(); //공유하된 마우스클릭상태
mouseClick = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 17) const mouseUserX	= PVariable(); //공유화된 마우스상대좌표X
mouseUserX = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 18) const mouseUserY	= PVariable(); //공유화된 마우스상대좌표Y
mouseUserY = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 19) const screenUserX	= PVariable(); //공유화된 화면X축 크기
screenUserX = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 22) const textUpdate	= PVariable(); //텍스트의 갱신이 필요할 때만 갱신하기 위한 변수
textUpdate = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 23) const colorL			= [Db(""), Db("\x1F")];
colorL = _CGFW(lambda: [_ARR(FlattenList([Db(""), Db("\x1F")]))], 1)[0]
# (Line 25) function variableInit(){ //MSQC에서 사용하기 위해 변수등록(?)
@EUDFunc
def f_variableInit():
    # (Line 26) EUDRegisterObjectToNamespace("readMode", readMode);
    EUDRegisterObjectToNamespace("readMode", readMode)
    # (Line 27) EUDRegisterObjectToNamespace("mouseClick", mouseClick);
    EUDRegisterObjectToNamespace("mouseClick", mouseClick)
    # (Line 28) EUDRegisterObjectToNamespace("screenSizeX", screenSizeX);
    EUDRegisterObjectToNamespace("screenSizeX", screenSizeX)
    # (Line 29) EUDRegisterObjectToNamespace("mouseUserX", mouseUserX);
    EUDRegisterObjectToNamespace("mouseUserX", mouseUserX)
    # (Line 30) EUDRegisterObjectToNamespace("mouseUserY", mouseUserY);
    EUDRegisterObjectToNamespace("mouseUserY", mouseUserY)
    # (Line 31) EUDRegisterObjectToNamespace("screenUserX", screenUserX);
    EUDRegisterObjectToNamespace("screenUserX", screenUserX)
    # (Line 32) }
    # (Line 34) const checkscreenLoc = $L("checkScreen");

checkscreenLoc = _CGFW(lambda: [GetLocationIndex("checkScreen")], 1)[0]
# (Line 35) function checkScreenMouse(){
@EUDFunc
def f_checkScreenMouse():
    # (Line 36) if(IsUserCP()){
    if EUDIf()(IsUserCP()):
        # (Line 37) mouseX = dwread_epd_safe(mouseMX);
        mouseX << (f_dwread_epd_safe(mouseMX))
        # (Line 38) mouseY = dwread_epd_safe(mouseMY);
        mouseY << (f_dwread_epd_safe(mouseMY))
        # (Line 39) screenGridX = dwread_epd(EPD(0x62848C));
        screenGridX << (f_dwread_epd(EPD(0x62848C)))
        # (Line 40) screenGridY = dwread_epd(EPD(0x6284A8));
        screenGridY << (f_dwread_epd(EPD(0x6284A8)))
        # (Line 41) setloc(checkscreenLoc, 128*16, 128*16); //중앙 (맵사이즈*16, 맵사이즈*16)
        f_setloc(checkscreenLoc, 128 * 16, 128 * 16)
        # (Line 42) CenterView(checkscreenLoc);
        # (Line 43) const ScreenX2 = dwread_epd(EPD(0x62848C));
        DoActions(CenterView(checkscreenLoc))
        ScreenX2 = f_dwread_epd(EPD(0x62848C))
        # (Line 44) const ScreenY2 = dwread_epd(EPD(0x6284A8));
        ScreenY2 = f_dwread_epd(EPD(0x6284A8))
        # (Line 45) screenSizeX = 128*16 - ScreenX2;
        screenSizeX << (128 * 16 - ScreenX2)
        # (Line 46) screenSizeY = 128*16 - ScreenY2;
        screenSizeY << (128 * 16 - ScreenY2)
        # (Line 47) const screenX = screenGridX + screenSizeX;
        screenX = screenGridX + screenSizeX
        # (Line 48) const screenY = screenGridY + screenSizeY;
        screenY = screenGridY + screenSizeY
        # (Line 49) setloc(checkscreenLoc, screenX, screenY);
        f_setloc(checkscreenLoc, screenX, screenY)
        # (Line 50) CenterView(checkscreenLoc);
        # (Line 51) }
        DoActions(CenterView(checkscreenLoc))
        # (Line 52) }
    EUDEndIf()
