## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) const bgmlen = [0x41424040, 0x41414040, 0x45414040, 0x41414040, 0x45414040, 0x46464040];
bgmlen = _CGFW(lambda: [_ARR(FlattenList([0x41424040, 0x41414040, 0x45414040, 0x41414040, 0x45414040, 0x46464040]))], 1)[0]
# (Line 2) const str = StringBuffer();
str = _CGFW(lambda: [StringBuffer()], 1)[0]
# (Line 3) function PlayOGG(bgmindex ,bgmcode, track){
@EUDFunc
def PlayOGG(bgmindex, bgmcode, track):
    # (Line 4) SetMemoryEPD(str.epd, SetTo, bgmcode);
    # (Line 5) SetMemoryEPD(str.epd + 1, SetTo, track);
    DoActions(SetMemoryEPD(str.epd, SetTo, bgmcode))
    # (Line 6) str.Play();
    DoActions(SetMemoryEPD(str.epd + 1, SetTo, track))
    str.Play()
    # (Line 8) if (MemoryEPD(EPD(bgmlen) + bgmindex, Exactly, track)){
    if EUDIf()(MemoryEPD(EPD(bgmlen) + bgmindex, Exactly, track)):
        # (Line 9) return 0;
        EUDReturn(0)
        # (Line 10) }else{
    if EUDElse()():
        # (Line 11) return 1;
        EUDReturn(1)
        # (Line 12) }
        # (Line 13) }
    EUDEndIf()
    # (Line 14) function loadSound(){

@EUDFunc
def f_loadSound():
    # (Line 15) EUDPlayerLoop()();
    EUDPlayerLoop()()
    # (Line 16) str.insert(0, '');
    str.insert(0, '')
    # (Line 17) str.append('@@@@@@@@');
    str.append('@@@@@@@@')
    # (Line 18) EUDEndPlayerLoop();
    EUDEndPlayerLoop()
    # (Line 19) MPQAddFile('@@@@@@@@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st0.ogg', 'rb').read());
    MPQAddFile('@@@@@@@@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st0.ogg', 'rb').read())
    # (Line 20) MPQAddFile('@@@@@@@A', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st1.ogg', 'rb').read());
    MPQAddFile('@@@@@@@A', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st1.ogg', 'rb').read())
    # (Line 21) MPQAddFile('@@@@@@@J', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st10.ogg', 'rb').read());
    MPQAddFile('@@@@@@@J', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st10.ogg', 'rb').read())
    # (Line 22) MPQAddFile('@@@@@@@K', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st11.ogg', 'rb').read());
    MPQAddFile('@@@@@@@K', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st11.ogg', 'rb').read())
    # (Line 23) MPQAddFile('@@@@@@@L', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st12.ogg', 'rb').read());
    MPQAddFile('@@@@@@@L', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st12.ogg', 'rb').read())
    # (Line 24) MPQAddFile('@@@@@@@M', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st13.ogg', 'rb').read());
    MPQAddFile('@@@@@@@M', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st13.ogg', 'rb').read())
    # (Line 25) MPQAddFile('@@@@@@@N', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st14.ogg', 'rb').read());
    MPQAddFile('@@@@@@@N', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st14.ogg', 'rb').read())
    # (Line 26) MPQAddFile('@@@@@@@O', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st15.ogg', 'rb').read());
    MPQAddFile('@@@@@@@O', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st15.ogg', 'rb').read())
    # (Line 27) MPQAddFile('@@@@@@A@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st16.ogg', 'rb').read());
    MPQAddFile('@@@@@@A@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st16.ogg', 'rb').read())
    # (Line 28) MPQAddFile('@@@@@@AA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st17.ogg', 'rb').read());
    MPQAddFile('@@@@@@AA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st17.ogg', 'rb').read())
    # (Line 29) MPQAddFile('@@@@@@AB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st18.ogg', 'rb').read());
    MPQAddFile('@@@@@@AB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st18.ogg', 'rb').read())
    # (Line 30) MPQAddFile('@@@@@@AC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st19.ogg', 'rb').read());
    MPQAddFile('@@@@@@AC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st19.ogg', 'rb').read())
    # (Line 31) MPQAddFile('@@@@@@@B', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st2.ogg', 'rb').read());
    MPQAddFile('@@@@@@@B', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st2.ogg', 'rb').read())
    # (Line 32) MPQAddFile('@@@@@@AD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st20.ogg', 'rb').read());
    MPQAddFile('@@@@@@AD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st20.ogg', 'rb').read())
    # (Line 33) MPQAddFile('@@@@@@AE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st21.ogg', 'rb').read());
    MPQAddFile('@@@@@@AE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st21.ogg', 'rb').read())
    # (Line 34) MPQAddFile('@@@@@@AF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st22.ogg', 'rb').read());
    MPQAddFile('@@@@@@AF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st22.ogg', 'rb').read())
    # (Line 35) MPQAddFile('@@@@@@AG', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st23.ogg', 'rb').read());
    MPQAddFile('@@@@@@AG', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st23.ogg', 'rb').read())
    # (Line 36) MPQAddFile('@@@@@@AH', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st24.ogg', 'rb').read());
    MPQAddFile('@@@@@@AH', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st24.ogg', 'rb').read())
    # (Line 37) MPQAddFile('@@@@@@AI', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st25.ogg', 'rb').read());
    MPQAddFile('@@@@@@AI', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st25.ogg', 'rb').read())
    # (Line 38) MPQAddFile('@@@@@@AJ', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st26.ogg', 'rb').read());
    MPQAddFile('@@@@@@AJ', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st26.ogg', 'rb').read())
    # (Line 39) MPQAddFile('@@@@@@AK', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st27.ogg', 'rb').read());
    MPQAddFile('@@@@@@AK', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st27.ogg', 'rb').read())
    # (Line 40) MPQAddFile('@@@@@@AL', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st28.ogg', 'rb').read());
    MPQAddFile('@@@@@@AL', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st28.ogg', 'rb').read())
    # (Line 41) MPQAddFile('@@@@@@AM', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st29.ogg', 'rb').read());
    MPQAddFile('@@@@@@AM', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st29.ogg', 'rb').read())
    # (Line 42) MPQAddFile('@@@@@@@C', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st3.ogg', 'rb').read());
    MPQAddFile('@@@@@@@C', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st3.ogg', 'rb').read())
    # (Line 43) MPQAddFile('@@@@@@AN', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st30.ogg', 'rb').read());
    MPQAddFile('@@@@@@AN', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st30.ogg', 'rb').read())
    # (Line 44) MPQAddFile('@@@@@@AO', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st31.ogg', 'rb').read());
    MPQAddFile('@@@@@@AO', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st31.ogg', 'rb').read())
    # (Line 45) MPQAddFile('@@@@@@B@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st32.ogg', 'rb').read());
    MPQAddFile('@@@@@@B@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st32.ogg', 'rb').read())
    # (Line 46) MPQAddFile('@@@@@@BA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st33.ogg', 'rb').read());
    MPQAddFile('@@@@@@BA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st33.ogg', 'rb').read())
    # (Line 47) MPQAddFile('@@@@@@@D', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st4.ogg', 'rb').read());
    MPQAddFile('@@@@@@@D', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st4.ogg', 'rb').read())
    # (Line 48) MPQAddFile('@@@@@@@E', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st5.ogg', 'rb').read());
    MPQAddFile('@@@@@@@E', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st5.ogg', 'rb').read())
    # (Line 49) MPQAddFile('@@@@@@@F', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st6.ogg', 'rb').read());
    MPQAddFile('@@@@@@@F', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st6.ogg', 'rb').read())
    # (Line 50) MPQAddFile('@@@@@@@G', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st7.ogg', 'rb').read());
    MPQAddFile('@@@@@@@G', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st7.ogg', 'rb').read())
    # (Line 51) MPQAddFile('@@@@@@@H', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st8.ogg', 'rb').read());
    MPQAddFile('@@@@@@@H', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st8.ogg', 'rb').read())
    # (Line 52) MPQAddFile('@@@@@@@I', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st9.ogg', 'rb').read());
    MPQAddFile('@@@@@@@I', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/0opening/st9.ogg', 'rb').read())
    # (Line 53) MPQAddFile('@@@A@@@@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st0.ogg', 'rb').read());
    MPQAddFile('@@@A@@@@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st0.ogg', 'rb').read())
    # (Line 54) MPQAddFile('@@@A@@@A', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st1.ogg', 'rb').read());
    MPQAddFile('@@@A@@@A', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st1.ogg', 'rb').read())
    # (Line 55) MPQAddFile('@@@A@@@J', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st10.ogg', 'rb').read());
    MPQAddFile('@@@A@@@J', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st10.ogg', 'rb').read())
    # (Line 56) MPQAddFile('@@@A@@@K', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st11.ogg', 'rb').read());
    MPQAddFile('@@@A@@@K', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st11.ogg', 'rb').read())
    # (Line 57) MPQAddFile('@@@A@@@L', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st12.ogg', 'rb').read());
    MPQAddFile('@@@A@@@L', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st12.ogg', 'rb').read())
    # (Line 58) MPQAddFile('@@@A@@@M', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st13.ogg', 'rb').read());
    MPQAddFile('@@@A@@@M', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st13.ogg', 'rb').read())
    # (Line 59) MPQAddFile('@@@A@@@N', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st14.ogg', 'rb').read());
    MPQAddFile('@@@A@@@N', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st14.ogg', 'rb').read())
    # (Line 60) MPQAddFile('@@@A@@@O', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st15.ogg', 'rb').read());
    MPQAddFile('@@@A@@@O', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st15.ogg', 'rb').read())
    # (Line 61) MPQAddFile('@@@A@@A@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st16.ogg', 'rb').read());
    MPQAddFile('@@@A@@A@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st16.ogg', 'rb').read())
    # (Line 62) MPQAddFile('@@@A@@AA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st17.ogg', 'rb').read());
    MPQAddFile('@@@A@@AA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st17.ogg', 'rb').read())
    # (Line 63) MPQAddFile('@@@A@@@B', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st2.ogg', 'rb').read());
    MPQAddFile('@@@A@@@B', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st2.ogg', 'rb').read())
    # (Line 64) MPQAddFile('@@@A@@@C', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st3.ogg', 'rb').read());
    MPQAddFile('@@@A@@@C', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st3.ogg', 'rb').read())
    # (Line 65) MPQAddFile('@@@A@@@D', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st4.ogg', 'rb').read());
    MPQAddFile('@@@A@@@D', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st4.ogg', 'rb').read())
    # (Line 66) MPQAddFile('@@@A@@@E', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st5.ogg', 'rb').read());
    MPQAddFile('@@@A@@@E', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st5.ogg', 'rb').read())
    # (Line 67) MPQAddFile('@@@A@@@F', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st6.ogg', 'rb').read());
    MPQAddFile('@@@A@@@F', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st6.ogg', 'rb').read())
    # (Line 68) MPQAddFile('@@@A@@@G', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st7.ogg', 'rb').read());
    MPQAddFile('@@@A@@@G', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st7.ogg', 'rb').read())
    # (Line 69) MPQAddFile('@@@A@@@H', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st8.ogg', 'rb').read());
    MPQAddFile('@@@A@@@H', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st8.ogg', 'rb').read())
    # (Line 70) MPQAddFile('@@@A@@@I', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st9.ogg', 'rb').read());
    MPQAddFile('@@@A@@@I', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/1스파이더맨/st9.ogg', 'rb').read())
    # (Line 71) MPQAddFile('@@@B@@@@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st0.ogg', 'rb').read());
    MPQAddFile('@@@B@@@@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st0.ogg', 'rb').read())
    # (Line 72) MPQAddFile('@@@B@@@A', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st1.ogg', 'rb').read());
    MPQAddFile('@@@B@@@A', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st1.ogg', 'rb').read())
    # (Line 73) MPQAddFile('@@@B@@@J', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st10.ogg', 'rb').read());
    MPQAddFile('@@@B@@@J', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st10.ogg', 'rb').read())
    # (Line 74) MPQAddFile('@@@B@@@K', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st11.ogg', 'rb').read());
    MPQAddFile('@@@B@@@K', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st11.ogg', 'rb').read())
    # (Line 75) MPQAddFile('@@@B@@@L', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st12.ogg', 'rb').read());
    MPQAddFile('@@@B@@@L', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st12.ogg', 'rb').read())
    # (Line 76) MPQAddFile('@@@B@@@M', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st13.ogg', 'rb').read());
    MPQAddFile('@@@B@@@M', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st13.ogg', 'rb').read())
    # (Line 77) MPQAddFile('@@@B@@@N', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st14.ogg', 'rb').read());
    MPQAddFile('@@@B@@@N', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st14.ogg', 'rb').read())
    # (Line 78) MPQAddFile('@@@B@@@O', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st15.ogg', 'rb').read());
    MPQAddFile('@@@B@@@O', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st15.ogg', 'rb').read())
    # (Line 79) MPQAddFile('@@@B@@A@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st16.ogg', 'rb').read());
    MPQAddFile('@@@B@@A@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st16.ogg', 'rb').read())
    # (Line 80) MPQAddFile('@@@B@@AA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st17.ogg', 'rb').read());
    MPQAddFile('@@@B@@AA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st17.ogg', 'rb').read())
    # (Line 81) MPQAddFile('@@@B@@AB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st18.ogg', 'rb').read());
    MPQAddFile('@@@B@@AB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st18.ogg', 'rb').read())
    # (Line 82) MPQAddFile('@@@B@@AC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st19.ogg', 'rb').read());
    MPQAddFile('@@@B@@AC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st19.ogg', 'rb').read())
    # (Line 83) MPQAddFile('@@@B@@@B', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st2.ogg', 'rb').read());
    MPQAddFile('@@@B@@@B', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st2.ogg', 'rb').read())
    # (Line 84) MPQAddFile('@@@B@@AD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st20.ogg', 'rb').read());
    MPQAddFile('@@@B@@AD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st20.ogg', 'rb').read())
    # (Line 85) MPQAddFile('@@@B@@AE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st21.ogg', 'rb').read());
    MPQAddFile('@@@B@@AE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st21.ogg', 'rb').read())
    # (Line 86) MPQAddFile('@@@B@@@C', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st3.ogg', 'rb').read());
    MPQAddFile('@@@B@@@C', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st3.ogg', 'rb').read())
    # (Line 87) MPQAddFile('@@@B@@@D', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st4.ogg', 'rb').read());
    MPQAddFile('@@@B@@@D', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st4.ogg', 'rb').read())
    # (Line 88) MPQAddFile('@@@B@@@E', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st5.ogg', 'rb').read());
    MPQAddFile('@@@B@@@E', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st5.ogg', 'rb').read())
    # (Line 89) MPQAddFile('@@@B@@@F', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st6.ogg', 'rb').read());
    MPQAddFile('@@@B@@@F', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st6.ogg', 'rb').read())
    # (Line 90) MPQAddFile('@@@B@@@G', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st7.ogg', 'rb').read());
    MPQAddFile('@@@B@@@G', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st7.ogg', 'rb').read())
    # (Line 91) MPQAddFile('@@@B@@@H', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st8.ogg', 'rb').read());
    MPQAddFile('@@@B@@@H', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st8.ogg', 'rb').read())
    # (Line 92) MPQAddFile('@@@B@@@I', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st9.ogg', 'rb').read());
    MPQAddFile('@@@B@@@I', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/2이누야샤/st9.ogg', 'rb').read())
    # (Line 93) MPQAddFile('@@@C@@@@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st0.ogg', 'rb').read());
    MPQAddFile('@@@C@@@@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st0.ogg', 'rb').read())
    # (Line 94) MPQAddFile('@@@C@@@A', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st1.ogg', 'rb').read());
    MPQAddFile('@@@C@@@A', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st1.ogg', 'rb').read())
    # (Line 95) MPQAddFile('@@@C@@@J', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st10.ogg', 'rb').read());
    MPQAddFile('@@@C@@@J', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st10.ogg', 'rb').read())
    # (Line 96) MPQAddFile('@@@C@@@K', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st11.ogg', 'rb').read());
    MPQAddFile('@@@C@@@K', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st11.ogg', 'rb').read())
    # (Line 97) MPQAddFile('@@@C@@@L', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st12.ogg', 'rb').read());
    MPQAddFile('@@@C@@@L', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st12.ogg', 'rb').read())
    # (Line 98) MPQAddFile('@@@C@@@M', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st13.ogg', 'rb').read());
    MPQAddFile('@@@C@@@M', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st13.ogg', 'rb').read())
    # (Line 99) MPQAddFile('@@@C@@@N', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st14.ogg', 'rb').read());
    MPQAddFile('@@@C@@@N', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st14.ogg', 'rb').read())
    # (Line 100) MPQAddFile('@@@C@@@O', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st15.ogg', 'rb').read());
    MPQAddFile('@@@C@@@O', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st15.ogg', 'rb').read())
    # (Line 101) MPQAddFile('@@@C@@A@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st16.ogg', 'rb').read());
    MPQAddFile('@@@C@@A@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st16.ogg', 'rb').read())
    # (Line 102) MPQAddFile('@@@C@@AA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st17.ogg', 'rb').read());
    MPQAddFile('@@@C@@AA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st17.ogg', 'rb').read())
    # (Line 103) MPQAddFile('@@@C@@@B', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st2.ogg', 'rb').read());
    MPQAddFile('@@@C@@@B', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st2.ogg', 'rb').read())
    # (Line 104) MPQAddFile('@@@C@@@C', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st3.ogg', 'rb').read());
    MPQAddFile('@@@C@@@C', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st3.ogg', 'rb').read())
    # (Line 105) MPQAddFile('@@@C@@@D', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st4.ogg', 'rb').read());
    MPQAddFile('@@@C@@@D', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st4.ogg', 'rb').read())
    # (Line 106) MPQAddFile('@@@C@@@E', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st5.ogg', 'rb').read());
    MPQAddFile('@@@C@@@E', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st5.ogg', 'rb').read())
    # (Line 107) MPQAddFile('@@@C@@@F', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st6.ogg', 'rb').read());
    MPQAddFile('@@@C@@@F', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st6.ogg', 'rb').read())
    # (Line 108) MPQAddFile('@@@C@@@G', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st7.ogg', 'rb').read());
    MPQAddFile('@@@C@@@G', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st7.ogg', 'rb').read())
    # (Line 109) MPQAddFile('@@@C@@@H', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st8.ogg', 'rb').read());
    MPQAddFile('@@@C@@@H', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st8.ogg', 'rb').read())
    # (Line 110) MPQAddFile('@@@C@@@I', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st9.ogg', 'rb').read());
    MPQAddFile('@@@C@@@I', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/3마비노기/st9.ogg', 'rb').read())
    # (Line 111) MPQAddFile('@@@D@@@@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st0.ogg', 'rb').read());
    MPQAddFile('@@@D@@@@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st0.ogg', 'rb').read())
    # (Line 112) MPQAddFile('@@@D@@@A', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st1.ogg', 'rb').read());
    MPQAddFile('@@@D@@@A', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st1.ogg', 'rb').read())
    # (Line 113) MPQAddFile('@@@D@@@J', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st10.ogg', 'rb').read());
    MPQAddFile('@@@D@@@J', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st10.ogg', 'rb').read())
    # (Line 114) MPQAddFile('@@@D@@@K', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st11.ogg', 'rb').read());
    MPQAddFile('@@@D@@@K', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st11.ogg', 'rb').read())
    # (Line 115) MPQAddFile('@@@D@@@L', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st12.ogg', 'rb').read());
    MPQAddFile('@@@D@@@L', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st12.ogg', 'rb').read())
    # (Line 116) MPQAddFile('@@@D@@@M', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st13.ogg', 'rb').read());
    MPQAddFile('@@@D@@@M', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st13.ogg', 'rb').read())
    # (Line 117) MPQAddFile('@@@D@@@N', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st14.ogg', 'rb').read());
    MPQAddFile('@@@D@@@N', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st14.ogg', 'rb').read())
    # (Line 118) MPQAddFile('@@@D@@@O', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st15.ogg', 'rb').read());
    MPQAddFile('@@@D@@@O', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st15.ogg', 'rb').read())
    # (Line 119) MPQAddFile('@@@D@@A@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st16.ogg', 'rb').read());
    MPQAddFile('@@@D@@A@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st16.ogg', 'rb').read())
    # (Line 120) MPQAddFile('@@@D@@AA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st17.ogg', 'rb').read());
    MPQAddFile('@@@D@@AA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st17.ogg', 'rb').read())
    # (Line 121) MPQAddFile('@@@D@@AB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st18.ogg', 'rb').read());
    MPQAddFile('@@@D@@AB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st18.ogg', 'rb').read())
    # (Line 122) MPQAddFile('@@@D@@AC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st19.ogg', 'rb').read());
    MPQAddFile('@@@D@@AC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st19.ogg', 'rb').read())
    # (Line 123) MPQAddFile('@@@D@@@B', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st2.ogg', 'rb').read());
    MPQAddFile('@@@D@@@B', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st2.ogg', 'rb').read())
    # (Line 124) MPQAddFile('@@@D@@AD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st20.ogg', 'rb').read());
    MPQAddFile('@@@D@@AD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st20.ogg', 'rb').read())
    # (Line 125) MPQAddFile('@@@D@@AE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st21.ogg', 'rb').read());
    MPQAddFile('@@@D@@AE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st21.ogg', 'rb').read())
    # (Line 126) MPQAddFile('@@@D@@@C', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st3.ogg', 'rb').read());
    MPQAddFile('@@@D@@@C', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st3.ogg', 'rb').read())
    # (Line 127) MPQAddFile('@@@D@@@D', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st4.ogg', 'rb').read());
    MPQAddFile('@@@D@@@D', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st4.ogg', 'rb').read())
    # (Line 128) MPQAddFile('@@@D@@@E', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st5.ogg', 'rb').read());
    MPQAddFile('@@@D@@@E', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st5.ogg', 'rb').read())
    # (Line 129) MPQAddFile('@@@D@@@F', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st6.ogg', 'rb').read());
    MPQAddFile('@@@D@@@F', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st6.ogg', 'rb').read())
    # (Line 130) MPQAddFile('@@@D@@@G', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st7.ogg', 'rb').read());
    MPQAddFile('@@@D@@@G', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st7.ogg', 'rb').read())
    # (Line 131) MPQAddFile('@@@D@@@H', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st8.ogg', 'rb').read());
    MPQAddFile('@@@D@@@H', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st8.ogg', 'rb').read())
    # (Line 132) MPQAddFile('@@@D@@@I', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st9.ogg', 'rb').read());
    MPQAddFile('@@@D@@@I', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/4셜록/st9.ogg', 'rb').read())
    # (Line 133) MPQAddFile('@@@E@@@@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st0.ogg', 'rb').read());
    MPQAddFile('@@@E@@@@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st0.ogg', 'rb').read())
    # (Line 134) MPQAddFile('@@@E@@@A', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st1.ogg', 'rb').read());
    MPQAddFile('@@@E@@@A', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st1.ogg', 'rb').read())
    # (Line 135) MPQAddFile('@@@E@@@J', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st10.ogg', 'rb').read());
    MPQAddFile('@@@E@@@J', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st10.ogg', 'rb').read())
    # (Line 136) MPQAddFile('@@@E@@FD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st100.ogg', 'rb').read());
    MPQAddFile('@@@E@@FD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st100.ogg', 'rb').read())
    # (Line 137) MPQAddFile('@@@E@@FE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st101.ogg', 'rb').read());
    MPQAddFile('@@@E@@FE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st101.ogg', 'rb').read())
    # (Line 138) MPQAddFile('@@@E@@FF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st102.ogg', 'rb').read());
    MPQAddFile('@@@E@@FF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st102.ogg', 'rb').read())
    # (Line 139) MPQAddFile('@@@E@@@K', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st11.ogg', 'rb').read());
    MPQAddFile('@@@E@@@K', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st11.ogg', 'rb').read())
    # (Line 140) MPQAddFile('@@@E@@@L', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st12.ogg', 'rb').read());
    MPQAddFile('@@@E@@@L', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st12.ogg', 'rb').read())
    # (Line 141) MPQAddFile('@@@E@@@M', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st13.ogg', 'rb').read());
    MPQAddFile('@@@E@@@M', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st13.ogg', 'rb').read())
    # (Line 142) MPQAddFile('@@@E@@@N', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st14.ogg', 'rb').read());
    MPQAddFile('@@@E@@@N', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st14.ogg', 'rb').read())
    # (Line 143) MPQAddFile('@@@E@@@O', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st15.ogg', 'rb').read());
    MPQAddFile('@@@E@@@O', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st15.ogg', 'rb').read())
    # (Line 144) MPQAddFile('@@@E@@A@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st16.ogg', 'rb').read());
    MPQAddFile('@@@E@@A@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st16.ogg', 'rb').read())
    # (Line 145) MPQAddFile('@@@E@@AA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st17.ogg', 'rb').read());
    MPQAddFile('@@@E@@AA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st17.ogg', 'rb').read())
    # (Line 146) MPQAddFile('@@@E@@AB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st18.ogg', 'rb').read());
    MPQAddFile('@@@E@@AB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st18.ogg', 'rb').read())
    # (Line 147) MPQAddFile('@@@E@@AC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st19.ogg', 'rb').read());
    MPQAddFile('@@@E@@AC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st19.ogg', 'rb').read())
    # (Line 148) MPQAddFile('@@@E@@@B', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st2.ogg', 'rb').read());
    MPQAddFile('@@@E@@@B', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st2.ogg', 'rb').read())
    # (Line 149) MPQAddFile('@@@E@@AD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st20.ogg', 'rb').read());
    MPQAddFile('@@@E@@AD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st20.ogg', 'rb').read())
    # (Line 150) MPQAddFile('@@@E@@AE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st21.ogg', 'rb').read());
    MPQAddFile('@@@E@@AE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st21.ogg', 'rb').read())
    # (Line 151) MPQAddFile('@@@E@@AF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st22.ogg', 'rb').read());
    MPQAddFile('@@@E@@AF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st22.ogg', 'rb').read())
    # (Line 152) MPQAddFile('@@@E@@AG', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st23.ogg', 'rb').read());
    MPQAddFile('@@@E@@AG', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st23.ogg', 'rb').read())
    # (Line 153) MPQAddFile('@@@E@@AH', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st24.ogg', 'rb').read());
    MPQAddFile('@@@E@@AH', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st24.ogg', 'rb').read())
    # (Line 154) MPQAddFile('@@@E@@AI', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st25.ogg', 'rb').read());
    MPQAddFile('@@@E@@AI', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st25.ogg', 'rb').read())
    # (Line 155) MPQAddFile('@@@E@@AJ', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st26.ogg', 'rb').read());
    MPQAddFile('@@@E@@AJ', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st26.ogg', 'rb').read())
    # (Line 156) MPQAddFile('@@@E@@AK', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st27.ogg', 'rb').read());
    MPQAddFile('@@@E@@AK', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st27.ogg', 'rb').read())
    # (Line 157) MPQAddFile('@@@E@@AL', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st28.ogg', 'rb').read());
    MPQAddFile('@@@E@@AL', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st28.ogg', 'rb').read())
    # (Line 158) MPQAddFile('@@@E@@AM', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st29.ogg', 'rb').read());
    MPQAddFile('@@@E@@AM', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st29.ogg', 'rb').read())
    # (Line 159) MPQAddFile('@@@E@@@C', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st3.ogg', 'rb').read());
    MPQAddFile('@@@E@@@C', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st3.ogg', 'rb').read())
    # (Line 160) MPQAddFile('@@@E@@AN', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st30.ogg', 'rb').read());
    MPQAddFile('@@@E@@AN', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st30.ogg', 'rb').read())
    # (Line 161) MPQAddFile('@@@E@@AO', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st31.ogg', 'rb').read());
    MPQAddFile('@@@E@@AO', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st31.ogg', 'rb').read())
    # (Line 162) MPQAddFile('@@@E@@B@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st32.ogg', 'rb').read());
    MPQAddFile('@@@E@@B@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st32.ogg', 'rb').read())
    # (Line 163) MPQAddFile('@@@E@@BA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st33.ogg', 'rb').read());
    MPQAddFile('@@@E@@BA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st33.ogg', 'rb').read())
    # (Line 164) MPQAddFile('@@@E@@BB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st34.ogg', 'rb').read());
    MPQAddFile('@@@E@@BB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st34.ogg', 'rb').read())
    # (Line 165) MPQAddFile('@@@E@@BC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st35.ogg', 'rb').read());
    MPQAddFile('@@@E@@BC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st35.ogg', 'rb').read())
    # (Line 166) MPQAddFile('@@@E@@BD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st36.ogg', 'rb').read());
    MPQAddFile('@@@E@@BD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st36.ogg', 'rb').read())
    # (Line 167) MPQAddFile('@@@E@@BE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st37.ogg', 'rb').read());
    MPQAddFile('@@@E@@BE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st37.ogg', 'rb').read())
    # (Line 168) MPQAddFile('@@@E@@BF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st38.ogg', 'rb').read());
    MPQAddFile('@@@E@@BF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st38.ogg', 'rb').read())
    # (Line 169) MPQAddFile('@@@E@@BG', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st39.ogg', 'rb').read());
    MPQAddFile('@@@E@@BG', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st39.ogg', 'rb').read())
    # (Line 170) MPQAddFile('@@@E@@@D', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st4.ogg', 'rb').read());
    MPQAddFile('@@@E@@@D', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st4.ogg', 'rb').read())
    # (Line 171) MPQAddFile('@@@E@@BH', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st40.ogg', 'rb').read());
    MPQAddFile('@@@E@@BH', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st40.ogg', 'rb').read())
    # (Line 172) MPQAddFile('@@@E@@BI', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st41.ogg', 'rb').read());
    MPQAddFile('@@@E@@BI', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st41.ogg', 'rb').read())
    # (Line 173) MPQAddFile('@@@E@@BJ', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st42.ogg', 'rb').read());
    MPQAddFile('@@@E@@BJ', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st42.ogg', 'rb').read())
    # (Line 174) MPQAddFile('@@@E@@BK', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st43.ogg', 'rb').read());
    MPQAddFile('@@@E@@BK', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st43.ogg', 'rb').read())
    # (Line 175) MPQAddFile('@@@E@@BL', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st44.ogg', 'rb').read());
    MPQAddFile('@@@E@@BL', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st44.ogg', 'rb').read())
    # (Line 176) MPQAddFile('@@@E@@BM', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st45.ogg', 'rb').read());
    MPQAddFile('@@@E@@BM', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st45.ogg', 'rb').read())
    # (Line 177) MPQAddFile('@@@E@@BN', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st46.ogg', 'rb').read());
    MPQAddFile('@@@E@@BN', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st46.ogg', 'rb').read())
    # (Line 178) MPQAddFile('@@@E@@BO', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st47.ogg', 'rb').read());
    MPQAddFile('@@@E@@BO', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st47.ogg', 'rb').read())
    # (Line 179) MPQAddFile('@@@E@@C@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st48.ogg', 'rb').read());
    MPQAddFile('@@@E@@C@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st48.ogg', 'rb').read())
    # (Line 180) MPQAddFile('@@@E@@CA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st49.ogg', 'rb').read());
    MPQAddFile('@@@E@@CA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st49.ogg', 'rb').read())
    # (Line 181) MPQAddFile('@@@E@@@E', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st5.ogg', 'rb').read());
    MPQAddFile('@@@E@@@E', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st5.ogg', 'rb').read())
    # (Line 182) MPQAddFile('@@@E@@CB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st50.ogg', 'rb').read());
    MPQAddFile('@@@E@@CB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st50.ogg', 'rb').read())
    # (Line 183) MPQAddFile('@@@E@@CC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st51.ogg', 'rb').read());
    MPQAddFile('@@@E@@CC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st51.ogg', 'rb').read())
    # (Line 184) MPQAddFile('@@@E@@CD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st52.ogg', 'rb').read());
    MPQAddFile('@@@E@@CD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st52.ogg', 'rb').read())
    # (Line 185) MPQAddFile('@@@E@@CE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st53.ogg', 'rb').read());
    MPQAddFile('@@@E@@CE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st53.ogg', 'rb').read())
    # (Line 186) MPQAddFile('@@@E@@CF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st54.ogg', 'rb').read());
    MPQAddFile('@@@E@@CF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st54.ogg', 'rb').read())
    # (Line 187) MPQAddFile('@@@E@@CG', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st55.ogg', 'rb').read());
    MPQAddFile('@@@E@@CG', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st55.ogg', 'rb').read())
    # (Line 188) MPQAddFile('@@@E@@CH', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st56.ogg', 'rb').read());
    MPQAddFile('@@@E@@CH', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st56.ogg', 'rb').read())
    # (Line 189) MPQAddFile('@@@E@@CI', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st57.ogg', 'rb').read());
    MPQAddFile('@@@E@@CI', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st57.ogg', 'rb').read())
    # (Line 190) MPQAddFile('@@@E@@CJ', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st58.ogg', 'rb').read());
    MPQAddFile('@@@E@@CJ', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st58.ogg', 'rb').read())
    # (Line 191) MPQAddFile('@@@E@@CK', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st59.ogg', 'rb').read());
    MPQAddFile('@@@E@@CK', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st59.ogg', 'rb').read())
    # (Line 192) MPQAddFile('@@@E@@@F', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st6.ogg', 'rb').read());
    MPQAddFile('@@@E@@@F', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st6.ogg', 'rb').read())
    # (Line 193) MPQAddFile('@@@E@@CL', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st60.ogg', 'rb').read());
    MPQAddFile('@@@E@@CL', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st60.ogg', 'rb').read())
    # (Line 194) MPQAddFile('@@@E@@CM', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st61.ogg', 'rb').read());
    MPQAddFile('@@@E@@CM', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st61.ogg', 'rb').read())
    # (Line 195) MPQAddFile('@@@E@@CN', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st62.ogg', 'rb').read());
    MPQAddFile('@@@E@@CN', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st62.ogg', 'rb').read())
    # (Line 196) MPQAddFile('@@@E@@CO', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st63.ogg', 'rb').read());
    MPQAddFile('@@@E@@CO', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st63.ogg', 'rb').read())
    # (Line 197) MPQAddFile('@@@E@@D@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st64.ogg', 'rb').read());
    MPQAddFile('@@@E@@D@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st64.ogg', 'rb').read())
    # (Line 198) MPQAddFile('@@@E@@DA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st65.ogg', 'rb').read());
    MPQAddFile('@@@E@@DA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st65.ogg', 'rb').read())
    # (Line 199) MPQAddFile('@@@E@@DB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st66.ogg', 'rb').read());
    MPQAddFile('@@@E@@DB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st66.ogg', 'rb').read())
    # (Line 200) MPQAddFile('@@@E@@DC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st67.ogg', 'rb').read());
    MPQAddFile('@@@E@@DC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st67.ogg', 'rb').read())
    # (Line 201) MPQAddFile('@@@E@@DD', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st68.ogg', 'rb').read());
    MPQAddFile('@@@E@@DD', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st68.ogg', 'rb').read())
    # (Line 202) MPQAddFile('@@@E@@DE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st69.ogg', 'rb').read());
    MPQAddFile('@@@E@@DE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st69.ogg', 'rb').read())
    # (Line 203) MPQAddFile('@@@E@@@G', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st7.ogg', 'rb').read());
    MPQAddFile('@@@E@@@G', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st7.ogg', 'rb').read())
    # (Line 204) MPQAddFile('@@@E@@DF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st70.ogg', 'rb').read());
    MPQAddFile('@@@E@@DF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st70.ogg', 'rb').read())
    # (Line 205) MPQAddFile('@@@E@@DG', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st71.ogg', 'rb').read());
    MPQAddFile('@@@E@@DG', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st71.ogg', 'rb').read())
    # (Line 206) MPQAddFile('@@@E@@DH', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st72.ogg', 'rb').read());
    MPQAddFile('@@@E@@DH', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st72.ogg', 'rb').read())
    # (Line 207) MPQAddFile('@@@E@@DI', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st73.ogg', 'rb').read());
    MPQAddFile('@@@E@@DI', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st73.ogg', 'rb').read())
    # (Line 208) MPQAddFile('@@@E@@DJ', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st74.ogg', 'rb').read());
    MPQAddFile('@@@E@@DJ', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st74.ogg', 'rb').read())
    # (Line 209) MPQAddFile('@@@E@@DK', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st75.ogg', 'rb').read());
    MPQAddFile('@@@E@@DK', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st75.ogg', 'rb').read())
    # (Line 210) MPQAddFile('@@@E@@DL', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st76.ogg', 'rb').read());
    MPQAddFile('@@@E@@DL', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st76.ogg', 'rb').read())
    # (Line 211) MPQAddFile('@@@E@@DM', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st77.ogg', 'rb').read());
    MPQAddFile('@@@E@@DM', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st77.ogg', 'rb').read())
    # (Line 212) MPQAddFile('@@@E@@DN', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st78.ogg', 'rb').read());
    MPQAddFile('@@@E@@DN', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st78.ogg', 'rb').read())
    # (Line 213) MPQAddFile('@@@E@@DO', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st79.ogg', 'rb').read());
    MPQAddFile('@@@E@@DO', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st79.ogg', 'rb').read())
    # (Line 214) MPQAddFile('@@@E@@@H', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st8.ogg', 'rb').read());
    MPQAddFile('@@@E@@@H', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st8.ogg', 'rb').read())
    # (Line 215) MPQAddFile('@@@E@@E@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st80.ogg', 'rb').read());
    MPQAddFile('@@@E@@E@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st80.ogg', 'rb').read())
    # (Line 216) MPQAddFile('@@@E@@EA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st81.ogg', 'rb').read());
    MPQAddFile('@@@E@@EA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st81.ogg', 'rb').read())
    # (Line 217) MPQAddFile('@@@E@@EB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st82.ogg', 'rb').read());
    MPQAddFile('@@@E@@EB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st82.ogg', 'rb').read())
    # (Line 218) MPQAddFile('@@@E@@EC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st83.ogg', 'rb').read());
    MPQAddFile('@@@E@@EC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st83.ogg', 'rb').read())
    # (Line 219) MPQAddFile('@@@E@@ED', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st84.ogg', 'rb').read());
    MPQAddFile('@@@E@@ED', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st84.ogg', 'rb').read())
    # (Line 220) MPQAddFile('@@@E@@EE', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st85.ogg', 'rb').read());
    MPQAddFile('@@@E@@EE', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st85.ogg', 'rb').read())
    # (Line 221) MPQAddFile('@@@E@@EF', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st86.ogg', 'rb').read());
    MPQAddFile('@@@E@@EF', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st86.ogg', 'rb').read())
    # (Line 222) MPQAddFile('@@@E@@EG', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st87.ogg', 'rb').read());
    MPQAddFile('@@@E@@EG', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st87.ogg', 'rb').read())
    # (Line 223) MPQAddFile('@@@E@@EH', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st88.ogg', 'rb').read());
    MPQAddFile('@@@E@@EH', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st88.ogg', 'rb').read())
    # (Line 224) MPQAddFile('@@@E@@EI', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st89.ogg', 'rb').read());
    MPQAddFile('@@@E@@EI', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st89.ogg', 'rb').read())
    # (Line 225) MPQAddFile('@@@E@@@I', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st9.ogg', 'rb').read());
    MPQAddFile('@@@E@@@I', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st9.ogg', 'rb').read())
    # (Line 226) MPQAddFile('@@@E@@EJ', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st90.ogg', 'rb').read());
    MPQAddFile('@@@E@@EJ', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st90.ogg', 'rb').read())
    # (Line 227) MPQAddFile('@@@E@@EK', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st91.ogg', 'rb').read());
    MPQAddFile('@@@E@@EK', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st91.ogg', 'rb').read())
    # (Line 228) MPQAddFile('@@@E@@EL', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st92.ogg', 'rb').read());
    MPQAddFile('@@@E@@EL', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st92.ogg', 'rb').read())
    # (Line 229) MPQAddFile('@@@E@@EM', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st93.ogg', 'rb').read());
    MPQAddFile('@@@E@@EM', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st93.ogg', 'rb').read())
    # (Line 230) MPQAddFile('@@@E@@EN', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st94.ogg', 'rb').read());
    MPQAddFile('@@@E@@EN', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st94.ogg', 'rb').read())
    # (Line 231) MPQAddFile('@@@E@@EO', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st95.ogg', 'rb').read());
    MPQAddFile('@@@E@@EO', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st95.ogg', 'rb').read())
    # (Line 232) MPQAddFile('@@@E@@F@', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st96.ogg', 'rb').read());
    MPQAddFile('@@@E@@F@', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st96.ogg', 'rb').read())
    # (Line 233) MPQAddFile('@@@E@@FA', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st97.ogg', 'rb').read());
    MPQAddFile('@@@E@@FA', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st97.ogg', 'rb').read())
    # (Line 234) MPQAddFile('@@@E@@FB', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st98.ogg', 'rb').read());
    MPQAddFile('@@@E@@FB', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st98.ogg', 'rb').read())
    # (Line 235) MPQAddFile('@@@E@@FC', py_open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st99.ogg', 'rb').read());
    MPQAddFile('@@@E@@FC', open('D:/OneDrive/Tools/EUD/스타/음악퀴즈 오픈소스 파일 ver8/BulidData_음악퀴즈 오픈소스/sound/5ending/st99.ogg', 'rb').read())
    # (Line 236) }
